### ISSUE TITLE
app file structure

### ISSUE THREAD

**Issue by Summer88** [Koed00/django-q#100]
I've already worked with django, sorry if this is a silly question.

This is the usual file structure:

project: 
            mydata_app
            manage.py
           
I should add the tasks to a file called tasks.py?
It should be inside mydata_app or in the projects directory?

the call for the tasks can be placed in the views.py?

**Comment by Eagllus** [comment]
Hi @Summer88,
I recommend placing all your tasks for related to a app in a file named tasks.py
example:
```
project:
    my_app/
        tasks.py

   my_other_app/
        tasks.py

   manage.py
```

The location you where you call a tasks is depend on where you want the task to go to the background.
Nice examples of this are available in the documentation.
https://django-q.readthedocs.org/en/latest/examples.html

**Comment by Koed00** [comment]
Django Q does not enforce a location for your task. It can be any function inside your environment.
As long as it's importable, you can run it as a task. However it is always good practice to keep things together in once place.

You can use imports:
``` python
from my_app import somefunction

async(somefunction, somearguments)
```

or full paths:

```python
async('my_app.somefunction', somearguments)
```

both do the same thing.

**Comment by Summer88** [comment]
Thanks for the explanation, I will try it out asap!
