### ISSUE TITLE
Q Cluster auto-launch?

### ISSUE THREAD

**Issue by kdmukai** [Koed00/django-q#102]
I'm trying to simplify local dev and my Production environment. I'd love a way to have each Django instance auto-launch a Q Cluster based on a settings.py param.

This would make it easy to eventually separate pure web front ends from task workers by just tweaking some if/else logic in the settings.py.

It looks like the place to put a run-once-on-launch command would be in myapp/app.py (see: http://stackoverflow.com/a/16111968)

I tried a naive:
```python
q = Cluster()
try:
	q.stop()
except Exception as e:
	pass
q.start()
```
in app.py but it isn't finding existing instances and is just spawning a new cluster each time. It also isn't able to fully shut down the clusters when runserver exits. Can you think of any better ways to couple a django instance with an auto-launched cluster? Or are there particular reasons why such a coupling is a bad idea?

**Comment by Koed00** [comment]
All clusters are forked processes so you will need the pid to be able to control it.
It is on my Todo list to add remote start/stop functionality to the `qmonitor` command, so you would be able to check if there are any clusters already running and act accordingly.

On whether it's a good idea I'm not sure. The system was designed to let you scale your web requests and your async requests separately. Even if you have 4 web server instances, you would probably only want one or two worker clusters to handle the async requests they generate. Also by running the cluster on the same machine/vm/container as your web server, you run the risk of slow web responses when the workers are handling an intensive job. Which is exactly what it was designed to prevent.
However, if you're just running the occasional schedule and async a couple of emails, then it probably wouldn't matter much.

Personally I would use a [process manager](http://django-q.readthedocs.org/en/latest/cluster.html#process-managers) like supervisor, honcho or circus to control the spawning of your web and cluster instances. At least that way you can handle unexpected crashes and scale up or down according to your needs.

**Comment by Eagllus** [comment]
In the example I noticed you use `copy_env = True` I cant seem to get that to work, so here's a little work around.

```
[watcher:django_q]
cmd=python manage.py qcluster --settings=<application.settings>
numprocesses=1
```
