### ISSUE TITLE
"connection already closed" while testing

### ISSUE THREAD

**Issue by mbi** [Koed00/django-q#127]
I'm trying to write tests for an app using django-q, so I thought just use the ORM broker and force tasks to run synchronously:

    Q_CLUSTER = {
        'sync': True,
        'orm': 'default'
    }

My test calls a function that enqueues a task, 

    Creating test database for alias 'default'...
    10:37:57 [Q] INFO Starting check on expired.identrustssl.com
    10:37:58 [Q] INFO MainProcess ready for work at 22161
    10:37:58 [Q] INFO MainProcess processing [potato-eight-west-jersey]
    10:38:00 [Q] INFO MainProcess stopped doing work
    10:38:00 [Q] INFO MainProcess monitoring at 22161
    10:38:00 [Q] ERROR connection already closed
    10:38:00 [Q] ERROR Failed [potato-eight-west-jersey] - connection already closed

Am I missing something?

**Comment by Koed00** [comment]
This should probably be fixed by #126 . I'll merge and release it soon.
