### ISSUE TITLE
Make orm polling interval configurable

### ISSUE THREAD

**Issue by kraiz** [Koed00/django-q#139]
Hey, i love this package for it's simplicy. Dont interprete the title as command. It just should be catchy.

I want to discuss to possibility of adding a setting or configuration option for the orm polling interval. Correct me if i'm wrong but this value (https://github.com/Koed00/django-q/blob/v0.7.14/django_q/brokers/orm.py#L64) is the reason for about 5 SELECT queries per second to the ``django_q_ormq`` table. I have nothing against this default value, if there's the chance to decrease to pressure to the database. But currently it's not possible to optout this high frequency.

I had some problems as i'm running on pretty low hardware (slower than raspberry, very bad io). I know that's very special but changing this constant works fine for me.

Another possibility would be to inherit from the orm broker, just overwrite the ``dequeue()`` with a super-call and an additional ``sleep()``. But there's no possibility to add a custom broker. There should be as this would be the django way, wouldn't?

Knowing that the simplicy cannot preserved by simply adding more and more options I'm pretty open for your thoughts on this and may be able to prepare a PR based on some hints from you.

**Comment by Koed00** [comment]
That's a great idea. The ORM broker was really just an experiment and I never expected so many people to use it over the other brokers. 
Based on your idea I've added a `poll` setting that defaults to 0.2 and is uses in both the ORM and MongoDB broker in commit af3b1da08f79b3b6a7820b2c34a9efe3ea5495fc .  If that solves the problem for you, I'll add it to the documentation and merge it.

**Comment by Koed00** [comment]
I'll think more about somehow being able to choose your own broker class , as long as it's based on one of the original broker classes. It is the Django way, as you say.

**Comment by kraiz** [comment]
Wow, that was fast. Great work!

On custom brokers...i think this opens your solution for more usecases and customization. I find this a good investment. There will be more requests for more settings and options and you may then have the option to argue for customization. If the custom broker option already had been included i never had opened this ticket.

Maybe something like this. But that's your choice...thanks anyway!
```python
'broker': 'myapp.qbroker.LongSleepingORMBroker`
```

**Comment by Koed00** [comment]
Well this was a quick fix and there is still room for some extra configuration options as far as I'm concerned. 
Yes, I was thinking exactly along those lines with the custom broker class. I'm adding it to my todo list.
Thanks for taking the time to suggest it.

**Comment by Koed00** [comment]
The changes have been merged and I'll do a new release by the end of the week.

**Comment by Koed00** [comment]
Both the polling and the custom broker class are now in the current release

**Comment by kraiz** [comment]
Removed my hack and updated my requirements file. Thanks man!
