### ISSUE TITLE
Worker recycle causes: "ERROR connection already closed"

### ISSUE THREAD

**Issue by grayb** [Koed00/django-q#144]
Hello, and thanks for this great Django app!  I'm using Python 3.4, Django 1.9.2, the latest django-q and the ORM broker backed by PostgreSQL.

It appears that when my worker recycles, it loses the ability to talk to the database.  Everything works fine up until that point. I've verified it is directly related to the `recycle` configuration parameter, and changing this changes the placement of the error accordingly.

The output below shows the issue I'm having while running 1 single worker.

`14:43:16 [Q] INFO Processed [zulu-montana-triple-michigan]`
`14:43:16 [Q] INFO recycled worker Process-1:1`
`14:43:16 [Q] INFO Process-1:4 ready for work at 22360`
`14:43:16 [Q] INFO Process-1:4 processing [maryland-king-queen-table]`
`14:43:17 [Q] INFO Process-1:4 processing [summer-mirror-mountain-september]`
`14:43:17 [Q] INFO Processed [maryland-king-queen-table]`
`14:43:17 [Q] INFO Process-1:4 processing [illinois-finch-orange-sodium]`
`14:43:17 [Q] ERROR server closed the connection unexpectedly`
        `This probably means the server terminated abnormally`
        `before or while processing the request.`

Can you provide any guidance?  

Thanks

**Comment by Koed00** [comment]
I think you found a bug with the recycle not closing the db connection. I'll see if I can replicate it and maybe fix it.

**Comment by grayb** [comment]
I have found that if I configure the `recycle` value in `Q_CLUSTER` to be `0`, the problem disappears, and the workers process the queue normally and without error.

**Comment by Koed00** [comment]
You could test it by adding:
```
from django.db import connection 
connection.close()
```
to the end of the task you're running.

**Comment by grayb** [comment]
I did try your recommendation before posting this issue.  Unfortunately it didn't seem to have any effect.  I have a suspicion that it is the Broker/Pusher that is losing its connection and not the actual task/worker.  I don't have any evidence of this though, just a hunch.

**Comment by Koed00** [comment]
You are probably right. I guess I will actually have to fire up the old steam kettles and debug this. It might take a day or two though, cause I'm swamped at the moment.

**Comment by grayb** [comment]
Check out that pull request.  I'm able to recycle workers in my cluster now with the connection error I was seeing above. You may have a better place to put that line.  I wasn't sure if the pusher or monitor reincarnations would also need it, and I'm not sure how to test for that anyhow.

**Comment by Koed00** [comment]
I can't really replicate the problem. I've been running a bunch of tests with ORM broker and the recycle set to 5 , with a single worker.  This makes me think the problem only occurs when the actual task accesses the database.

**Comment by Koed00** [comment]
I've moved the connection closing to the point where the workers exit. This ensures it happens in the same thread. It also closes all connections, in case someone uses multiple connections.

Since I can't really replicate the problem at the moment, do you mind giving the Dev branch a spin?

**Comment by grayb** [comment]
I removed my change, and put the `db.connections.close_all()` on line 391 like you have it in the dev branch.  In this case, I still see the error, `ERROR server closed the connection unexpectedly`.

**Comment by grayb** [comment]
Thinking about it more, I do believe this connection closing belongs in `reincarnate()`.  When we spawn a new worker, we are getting a process copied from the current stack.  Closing the connection just before ensures an old descriptor or connection doesn't get copied and reused in the new process.

**Comment by Koed00** [comment]
You're on the right track. It's actually a security 'feature' of Postgres that connections can't be shared between threads. That's what causing the error. 
Well, that and Django not closing the connection after every transaction as it should. Or are you per chance using the `CONN_MAX_AGE` setting? That would explain why I can't replicate this.

I agree that it should happen in the `reincarnate` method. If any connections are still open, they should be killed there to prevent thread crossover.

**Comment by grayb** [comment]
I am not specifying `CONN_MAX_AGE`.  My database access inside the task function is limited to using a handful of Django model managers to retrieve by passed-in PK. for example: 

```
from base.models import ObjectRecord

task_func(obj_pk):
    ObjectRecord.objects.get(pk=obj_pk)
```

**Comment by Koed00** [comment]
Could you give the dev version a try again?  Seeing as I don't really have a test for this.

**Comment by grayb** [comment]
Sorry for the delay, I was able to try the new code (I caught it in master with an update).  It works perfectly, no more issues with recycled workers and the database.

Thanks!
