### ISSUE TITLE
Allow task custom name

### ISSUE THREAD

**Issue by k4ml** [Koed00/django-q#146]
Currently this is not possible:-

```python
task_id = async('send_sms', user_id, sender, recipient, message,
                          msgid, start_sending_time, name=msgid)
```

This I guess due to this code, which limit what task attributes you can override:-

```python
def async(func, *args, **kwargs):
    """Queue a task for the cluster."""
    keywords = kwargs.copy()
    opt_keys = ('hook', 'group', 'save', 'sync', 'cached', 'iter_count', 'iter_cached', 'chain', 'broker')
    q_options = keywords.pop('q_options', None)
    # get an id
    tag = uuid()
    # build the task package
    task = {'id': tag[1],
            'name': tag[0],
            'func': func,
            'args': args}
    # push optionals
    for key in opt_keys:
        if q_options and key in q_options:
            task[key] = q_options[key]
        elif key in keywords:
            task[key] = keywords.pop(key)
```

**Comment by Koed00** [comment]
I can add that without much trouble. Just never had someone request it before.

**Comment by k4ml** [comment]
Having support for custom name would be great !

**Comment by Koed00** [comment]
Ah, I remember now why I didn't do that in the first place.
I thought that 'name' was such a common argument name, that it would cause problems with the task functions. Maybe if I change it to task_name

**Comment by Koed00** [comment]
Ok. The dev version now has an optional `task_name` argument for tasks.

**Comment by k4ml** [comment]
Thanks ! We have been using django-q in production now.

**Comment by tylerautera** [comment]
@Koed00 is this `task_name` argument still in place for the latest version? I would also like to apply a custom name to my task as I have a need for users to have visibility on queued tasks on the front-end.

**Comment by k4ml** [comment]
It's there.

https://github.com/Koed00/django-q/blob/master/django_q/tasks.py#L43
