### ISSUE TITLE
Workflow need to run qcluster?

### ISSUE THREAD

**Issue by Summer88** [Koed00/django-q#156]
I've tried to add a simple task as async:

`task_id=async('my_app.tasks.print', self.pk)`

it run correctly if I start in a separate shell:

`python manage.py qcluster`

My question is: for deploy, the qcluster should always be started manually?

**Comment by k4ml** [comment]
You should start is as system daemon, either by adding it as init script, or using tools such as supervisord or daemontools. We use daemontools start qcluster as daemon - https://cr.yp.to/daemontools.html

More simple solution is to add it under your crontab as @reboot:-

```
crontab -l
@reboot /path/to/python /path/to/your_project/manage.py qcluster
```
