### ISSUE TITLE
Successful tasks are not being saved to the database when 'save_limit' config setting is 0

### ISSUE THREAD

**Issue by kefin** [Koed00/django-q#157]
The `django-q` docs says:

    save_limit
    Limits the amount of successful tasks saved to Django.

    - Set to 0 for unlimited.
    - Set to -1 for no success storage at all.
    - Defaults to 250
    - Failures are always saved.

I have `save_limit` set to `0` in my config:

        Q_CLUSTER = {
        ...
        'save_limit': 0,
        ....
    }

but none of the successful tasks are being saved to the db.

Setting `save_limit` to a positive value works, though.

I'm thinking line 402 from the `save_task` function in `cluster.py` may be the culprit:

    # SAVE LIMIT < 0 : Don't save success
    if not task.get('save', Conf.SAVE_LIMIT > 0) and task['success']:
        return

and `Conf.SAVE_LIMIT > 0` should be `Conf.SAVE_LIMIT >= 0`:

    # SAVE LIMIT < 0 : Don't save success
    if not task.get('save', Conf.SAVE_LIMIT >= 0) and task['success']:
        return

Or am I overlooking something in my config?

**Comment by Koed00** [comment]
Yep, another good spot. Thanks for taking the time to point this out.
I'll fix this soon.
