### ISSUE TITLE
Typo in parameter passed to broker in get_broker

### ISSUE THREAD

**Issue by kefin** [Koed00/django-q#158]
In the `get_broker` function in `brokers.__init__.py`, when returning a broker for a custom broker class (`Conf.BROKER_CLASS`), the parameter passed to `broker` is currently:

    if Conf.BROKER_CLASS:
        module, func = Conf.BROKER_CLASS.rsplit('.', 1)
        m = importlib.import_module(module)
        broker = getattr(m, func)
        return broker(list_key=list)

The last line above (line 166 in `brokers.__init__.py`) should use `list_key=list_key` instead of `list_key=list` as parameter to the `broker` function call:

    if Conf.BROKER_CLASS:
        module, func = Conf.BROKER_CLASS.rsplit('.', 1)
        m = importlib.import_module(module)
        broker = getattr(m, func)
        return broker(list_key=list_key)

The typo as it is now causes custom broker classes to fail when trying to connect because the `list_key` (with the value as a `list` class) causes a bad connection URL.

**Comment by Koed00** [comment]
Good spot. Fixed it and I'll release it soon.
