### ISSUE TITLE
ERROR invalid syntax (<unknown>, line 1) - while passing objects as arguments

### ISSUE THREAD

**Issue by dacodekid** [Koed00/django-q#170]
I'm not sure, its a SO question or bug.  My goal is to `schedule` a bulk mail task that sends with few attachments (will be included from a `django-admin` form page). Instead sending all at once, I also want to `schedule` them at random time.

The provided example from [Docs](http://django-q.readthedocs.io/en/latest/examples.html#emails) is perfect for sending a single email without attachments. But when I try to implement this with `django`'s `EmailMessage` with below code, I'm receiving `ERROR invalid syntax (<unknown>, line 1)` - error from `./manage.py qcluster`.

``` python
def send_email(email):
    pass


class VendorEmailView(View):

    @method_decorator(staff_member_required)
    def get(self, request):
        form = EmailForm({
            'subject': 'Test Subject',
            'message': 'Test Message',
        })
        return render(request, 'admin/project/vendor/email.html', {'form': form})

    @method_decorator(staff_member_required)
    def post(self, request):
        form = EmailForm(request.POST, request.FILES)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message'].replace(
                '/media/', 'http://{}/media/'.format(settings.ALLOWED_HOSTS[0]))

            email = EmailMessage(subject=subject, body=message, from_email='DaCodeKid@dacodekid.ocm')
            email.content_subtype = 'html'

            for attachment in request.FILES.getlist('attachment'):
                email.attach(attachment.name, attachment.read(), attachment.content_type)

            vendors = Vendor.objects.filter(primary_email__contains='@')
            for vendor in vendors:
                email.to = [vendor.primary_email]
                schedule('project.views.send_email',
                         email, #============> ERROR LINE <==================
                         schedule_type=Schedule.ONCE,
                         next_run=timezone.now() + timedelta(seconds=random.randint(1,1000))
                         )

            return redirect('/admin/project/vendor/', permanent=True)
```

The error raises whenever I try to pass an object (`email1 or`request`, etc) to my`send_email`function. It works fine when I'm passing variables like`subject`,`message`. 

Would appreciate your help.

**Comment by aeikenberry** [comment]
I'm not sure if this is a bug or not, but couldn't you move your Email implementation to the `send_email` function by passing strings into it (like the docs show)? Just a thought! Good luck.

**Comment by Eagllus** [comment]
@dacodekid did you ever resolve the problem?

**Comment by dacodekid** [comment]
@Eagllus sorry but I no longer use this package.

**Comment by Eagllus** [comment]
@dacodekid np, thanks for responding.

**Comment by fonzmeister** [comment]
I have a similiar problem. Not trying to send an email. Put parsing objects into a function or returning those raises this error

**Comment by jlev** [comment]
Yep, you need to pass an ID or a string representation of the object you want to use later. And then look it up in the scheduled function or hook. Not a great error message, but this issue was google-able enough.

**Comment by JocelynDelalande** [comment]
Same issue for me. 
Bumping this issue because I think it is a real one as :

- AFAIK what is supported and what is not as task function argument is not mentioned in docs,
- the error message is not helping at all and does not come with a stacktrace (hard debugging)

**Comment by marcelfranca** [comment]
Same issue for me.

This message keeps showing while the worker is either idle or performing a task.

I use async_tasks to sync files between django and AWS S3 and in the worker that this message is showing the task takes more time than workers that are not. 

All workers have similar hardware and are on the same LAN.

Was using version 1.3.2, updating to version 1.3.4 did not changed anything.

**Comment by millerthegorilla** [comment]
I have just had this issue, and the error message sucks.  This is almost the only place to discover that django_q schedule doesn't pass objects, but it makes sense that in the context of the module method that is called from the schedule, the objects are not going to be understood, even if they have been imported.
I solved this by passing ```my_model._meta.app_label + '.' + my_model._meta.object_name``` and in the called function using 
```python
from django.apps import apps
my_model = apps.get_model(*model_parameter.split('.'))
```
or words to that effect, since my project is closed, so its from memory.  I guess one can just pass the app_label and object_name as separate strings, and then call ```apps.get_model(app_label, object_name)```

**Comment by valeriuv** [comment]
I am getting this error as well in production (DEBUG=False), but not in development. Haven't found a solution yet (I don't seem to pass objects to the async_task). Extremely frustrating.

**Comment by valeriuv** [comment]
> I am getting this error as well in production (DEBUG=False), but not in development. Haven't found a solution yet (I don't seem to pass objects to the async_task). Extremely frustrating.

So in my case the issue was that I was passing kwargs in the args field in the admin interface.
