### ISSUE TITLE
ValueError('need more than 1 value to unpack',)

### ISSUE THREAD

**Issue by rwoloszyn** [Koed00/django-q#171]
I am testing django-q as production msg que and schedule library. I made simple function:
```python
@login_required
def makea_math(request):
    resp = {}
    resp['retrr'] = result(async('math_task', '123131.12312'), 100)
return HttpResponse(json.dumps(resp), content_type="application/json")
...
def math_task(number):
    return math.ceil(number)
```
but each time I get the error from broker:
`ValueError('need more than 1 value to unpack'`

Is there any way to debug or check broker logs and check what went wrong ?

I am running Django : 1.9.6
Django REST framework: 3.3.2

**Comment by thinkwelltwd** [comment]
I would check the resulting Task object that was created; I've gotten that error when the task had no args / kwargs.

**Comment by qb1989** [comment]
I just implemented your code snippet and debugged it.
The error comes not from the Broker but from the Cluster itself in line:360
Seems like there are some probs on how the functions (eg. math_task) are imported cause there is no problem with your code when you create a task.py which contains all your django_q tasks.

So maybe try to create a task.py file containing all your tasks and execute them like this:
`
async('examplepath.tasks.math_task', 123131.12312)`

**Comment by Koed00** [comment]
yes @qb1989 is right.

You either reference the function directly without quotes:

``` python
@login_required
def makea_math(request):
    resp = {}
    resp['retrr'] = result(async(math_task, '123131.12312'), 100)
return HttpResponse(json.dumps(resp), content_type="application/json")
```
This works fine with local functions and classes.

Or you have to use the full paths to the functions:

```python
@login_required
def makea_math(request):
    resp = {}
    resp['retrr'] = result(async('my_project.views.math_task', '123131.12312'), 100)
return HttpResponse(json.dumps(resp), content_type="application/json")
```
This is what I tend to do all the time.

The reason you see that error, is cause you are feeding the `result` function the import error as its first parameter.

**Comment by rwoloszyn** [comment]
@ Koed00  thanks. That was exactly the issue. I managed to fix this before your answer but thanks 
for help anyway.

**Comment by Koed00** [comment]
Awesome. Sorry, sometimes I don't respond as fast as I'd like to. 
Enjoy 👍

**Comment by sato-s** [comment]
This library is very useful and I really appreciate for it.
But, this behavior is completely cryptic.

In my case.

```python
async('async_tasks.finish_practice', 3, sync=True)
```
results in ``` No module named 'async_tasks'```

```python
async(async_tasks.finish_practice, 3, sync=True)
```

works without problem.

Could you reopen and shed light on this issue?

- Python 3.6.2
- django-q 0.9.0
- django 2.0

**Comment by Koed00** [comment]
If you are going to use the quoted path you will have to include the base module:

`async('my_main_module.tasks.async_tasks.finish_practice', 3, sync=True)`

That string needs to be importable from the root.
