### ISSUE TITLE
Can not pass async() non-core functions

### ISSUE THREAD

**Issue by davewilliamstx** [Koed00/django-q#178]
I have views.py and tasks.py in my project folder. 

I have the following in views.py:
```python
# views.py
def TestAsync(request):
    from django_q.tasks import async
    import tasks

    async('tasks.hi', 'Hooray!')

    return HttpResponseRedirect('blah')
```

and tasks.py is:
```python
# tasks.py
def hi(string_to_print):
    print string_to_print
```

When I hit the url I have wired to call my TestAsync view, I get the following error:

`'module' object has no attribute 'hi'`

I am able, however, to get the[ email examples](https://django-q.readthedocs.io/en/latest/examples.html) from the django-q docs working, among other examples that use functions from django core/python built-ins. I've tried passing the function to async() with and without quotes, tried putting the 'hi' function right in the view, and every importing scheme I can think of...I still get the same error.

I have a feeling that this might be an error caused my my lack of understanding on what constitutes an acceptable function to pass to async() - however on the off chance it's a bug I wanted to drop a note here. 

If it's my fault, perhaps it will help others to have a lower-level explanation of what async() expects from it's functions?

**Comment by Koed00** [comment]
You need to point to tasks.py with it's full path, which would include the project or root, 
i.e. `'myapp.tasks.hi'`.
This is because you're not restricted to executing only local functions.

**Comment by davewilliamstx** [comment]
I quickly tried adding the import `from tasks import hi` to the view, and then calling it directly, ie: `async(hi)` and I still get: `'module' object has no attribute 'hi'`. Also tried passing the full path in quotes, no dice.

I really hope I'm not just doing something dumb, but I really think this should be working.

**Comment by davewilliamstx** [comment]
As I suspected, it was me being dumb. Import redundancies in my views.py.
