### ISSUE TITLE
[Q] ERROR reincarnated pusher Process-1:4439 after sudden death

### ISSUE THREAD

**Issue by kellerkind** [Koed00/django-q#188]
I did some small test of django-q via the wonderful readthedocs guide which describes much simpler initial setup then with celery nowadays.

On my first tests I accidently had an error in tasks.py so the async task failed of course:

	19:56:55 [Q] ERROR global name 'sleep' is not defined
	19:57:05 [Q] INFO Process-1:4442 stopped pushing tasks
	19:57:05 [Q] ERROR reincarnated pusher Process-1:4442 after sudden death

What worries me is the 3rd line and that the log is now polluted with retries of reincarnation tasks. Is it configurable somehow that tasks with "sudden death" are not retried? Is it possible to modify the tasks file without necessity to restart the cluster afterwards?

**Comment by Koed00** [comment]
It is not the task that is being reincarnated, it is the task pusher that sits between the queue and the worker cluster.  You can refer to the [architecture](https://django-q.readthedocs.io/en/latest/architecture.html) page to see how it works.

Since every process in the architecture is a complete forked copy of your entire django module, a problem with your global will affect every part, not just an individual task.

I can't make any comments about your retry setup , without knowing what broker you are using.

**Comment by kellerkind** [comment]
Sorry,

issue comes up from a missing _import_ in the custom broker:

settings.py:

	Q_CLUSTER = {
	    'name': 'DjangORM',
	    'workers': 4,
	    'timeout': 90,
	    'retry': 120,
	    'queue_limit': 50,
	    'bulk': 10,
	    'orm': 'default',
	    'broker_class': 'jobs.broker.CustomOrmBroker'
	}

broker.py:

	''' fix import error '''	
	from time import sleep

	from django.utils import timezone
	from datetime import timedelta
	from django_q.brokers.orm import ORM
	from django_q.conf import Conf, logger

	from .models import TaskState

	def _timeout():
	    return timezone.now() - timedelta(seconds=Conf.RETRY)

	class CustomOrmBroker(ORM):

	    def enqueue(self, task):
		package = self.get_connection().create(key=self.list_key, payload=task, lock=_timeout())
		TaskState.objects.update_or_create(ormq=package,task_state='Open')
		return package.pk

	    def dequeue(self):
		tasks = self.get_connection().filter(key=self.list_key, lock__lt=_timeout())[0:Conf.BULK]
		if tasks:
		    task_list = []
		    lock = timezone.now()
		    for task in tasks:
		        TaskState.objects.filter(ormq__exact=task).update(task_state='Progress')

		        task.lock = lock
		        task.save(update_fields=['lock'])
		        task_list.append((task.pk, task.payload))
		    return task_list
		# empty queue, spare the cpu
		sleep(Conf.POLL)
