### ISSUE TITLE
Can't get attribute 'simple_class_factory' on module 'django.db.models.base'

### ISSUE THREAD

**Issue by canarduck** [Koed00/django-q#191]
```
Exception Value: 	
Can't get attribute 'simple_class_factory' on module 'django.db.models.base' 
Exception Location:
/django_q/signing.py in loads, line 44
```

Getting this error after updating to django 1.10 when I try to reach the "Queued tasks" admin page (django_q/ormq/)

* django 1.10
* django-q 0.7.18
* broker : Django ORM

It looks like the attribute was removed after 1.10a1 see https://github.com/django/django/commit/7f51876f99851fdc3fef63aecdfbcffa199c26b9

Thanks

**Comment by Koed00** [comment]
Have you tried clearing your queue?
Django doesn't support unsigning ( and unpickling) objects that have been signed with a previous version.

**Comment by canarduck** [comment]
Thanks a lot for the ultra quick response, I didn't know about this.
The queue is working again after a `brocker.delete_queue()`.
