### ISSUE TITLE
Limit number of retries

### ISSUE THREAD

**Issue by tremby** [Koed00/django-q#194]
When a task fails (like an unhandled exception) it is thrown in the failing jobs list but also retried. It doesn't seem there's any limit to the number of retries, and that means a job which is doomed to failure (due to my bad programming) continues to fail all day. I get a message sent to Rollbar each time, and that adds up to a lot of messages and eats my quota.

Is there a way to set a retry limit?

**Comment by manuganji** [comment]
Is there a work around for this?

**Comment by DEKHTIARJonathan** [comment]
Is there any update on this ? I have the exact same issue ...
@tremby @manuganji did you find a workaround ?

**Comment by tremby** [comment]
I honestly don't recall, but I don't think so. Sorry!

**Comment by manuganji** [comment]
No, I haven't found it. I just fixed that scenario where my task was failing and made sure that I covered all the scenarios that I could predict. An ugly workaround is to wrap your whole task code in a `try except` block and only throw known exceptions and absorb all others. Of course, this only works if you have limited task types.

**Comment by Eagllus** [comment]
One way I resolved this issue is with a function called `retry`
This is designed to work with `iLO's` that are unreliable with there response/connections.

```
def retry(func, *args, **kwargs):
    """
    a custom retry for setting iLO information
    """
    count = kwargs.get('count', 0)
    max_retries = kwargs.get('max_retries', 3)
    countdown = kwargs.get('countdown', 30)
    exc = kwargs.get('exc', BaseException)

    if count < max_retries:
        time.sleep(countdown)
        count += 1
        func(*args, count=count, max_retries=max_retries, countdown=countdown)
    else:
        raise exc
```

I used it like this

```
def set_host_power(ilo, values, **kwargs):
    try:
        return ilo.call_ilo('set_host_power_saver', values['host_power_saver'])
    except (IloCommunicationError, socket.timeout, socket.error) as exc:
        return retry(set_host_power, ilo, values, exc=exc, **kwargs)
```

This will make allow `retry` to retry it an `max_retries (default: 3)` before raising the exception.
You could instead return a state instead of raising the exception.

**Comment by dangerski** [comment]
If you are using AWS SQS, my workaround is to make a deadletter queue and then on your task queue enable "use redrive policy" which "Sends messages into a dead letter queue after exceeding the Maximum Receives." Then set the maximum receives to the amount of retries you want to allow.

**Comment by pilgrim2go** [comment]
@dangerski :  I have the same problem but even if I configure AWS Queue to use redrive. It doesn't help.
Diving into code to see why.

**Comment by mm-matthias** [comment]
The ack_failure/ack_failures options do not work for tasks that fail due to timeout. After the worker is killed, tasks remain in the queue. Once the worker is reincarnated, it fetches the task, runs into timeout and the whole things starts all over again.

**Comment by Waszker** [comment]
@mm-matthias I have exactly the same problem. Have you found the solution for it? It there a way to specify number of retries before termination?

**Comment by mm-matthias** [comment]
@Waszker We are using celery/redis instead of django-q for more than a year, so I don't have a solution for this problem

**Comment by Waszker** [comment]
> @Waszker We are using celery/redis instead of django-q for more than a year, so I don't have a solution for this problem

That'a a pity... Thanks for the answer though...

**Comment by timomeara** [comment]
i have a PR for a retry limit
https://github.com/Koed00/django-q/pull/466
try it out :)

**Comment by abhishek-compro** [comment]
This can be closed
