### ISSUE TITLE
django-q collides with existing app of name `tasks`

### ISSUE THREAD

**Issue by thekorn** [Koed00/django-q#199]
with putting django_q in installed apps of a django project, django_q itself is put as very first item of `sys.path``

``` python
>>> import sys
>>> sys.path
['/usr/lib/python2.7/site-packages/django_q', '/code/myproject', '/code/myproject', '/usr/lib/python27.zip', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-linux2', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/site-packages']
>>> import tasks
>>> tasks.__file__
'/usr/lib/python2.7/site-packages/django_q/tasks.pyc'
>>>
```

related code is at (https://github.com/Koed00/django-q/blob/master/django_q/__init__.py#L6)

This is problematic as it is polluting python's namespace with general purpose modules like `tasks`, `conf` and `cluster`

Also it is impossible to add a (or use an existing) app named `tasks`:

``` bash
⇒  docker-compose run web django-admin startapp tasks
CommandError: 'tasks' conflicts with the name of an existing Python module and cannot be used as an app name. Please try another name.
```

**Comment by thekorn** [comment]
This issue is the root cause for https://github.com/Koed00/django-q/issues/193

**Comment by raonyguimaraes** [comment]
You just change the name of the apps to qtasks, qconf and qcluster.
