### ISSUE TITLE
Starting qcluster crashes python in OSX Sierra

### ISSUE THREAD

**Issue by daniel-keller** [Koed00/django-q#201]
I have a simple script that calls async() to query and store data using sqlite. The script is able to queue the tasks without trouble but if I start `manage.py qcluster` Python immediately crashes with a segmentation fault. This occurs regardless of there being any tasks in the queue. I am using the Django ORM as a broker.

Python - 2.7.10
Django - 1.9.7
django-q - 0.7.18
OSX - 10.12

qcluster output before crash

> 18:16:15 [Q] INFO Q Cluster-62794 starting.
> 18:16:15 [Q] INFO Process-1:1 ready for work at 62796
> 18:16:15 [Q] INFO Process-1:2 ready for work at 62797
> 18:16:15 [Q] INFO Process-1:3 ready for work at 62798
> 18:16:15 [Q] INFO Process-1 guarding cluster at 62795
> 18:16:15 [Q] INFO Process-1:4 ready for work at 62799
> 18:16:15 [Q] INFO Process-1:5 monitoring at 62800
> 18:16:15 [Q] INFO Q Cluster-62794 running.
> 18:16:15 [Q] INFO Process-1:6 pushing tasks at 62801

Probably less helpful OSx crash report

> Process:           Python [62925]
> Path:             /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
> Identifier:            Python
> Version:               2.7.10 (2.7.10)
> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000110
> Exception Note:        EXC_CORPSE_NOTIFY
> Termination Signal:    Segmentation fault: 11
> Termination Reason:    Namespace SIGNAL, Code 0xb
> Terminating Process:   exc handler [0]

**Comment by alexgustafson** [comment]
I have the same problem.

python: 2.7.10
django: 1.10.2
django-q: 0.7.18
osx: 10.12.1

same output as above, then quits immediately with:
Process finished with exit code 0

 I am not sure where to find the python crash report.

**Comment by Eagllus** [comment]
Could you try it with python 3?
I have the following setup

python: 3.5.0
django: 1.10.2
django-q: 0.7.18
osx: 10.12.1

so the only difference would be the python version

**Comment by alexgustafson** [comment]
Yes, with python 3 it works.
