### ISSUE TITLE
send_mail problem

### ISSUE THREAD

**Issue by alexgustafson** [Koed00/django-q#202]
I can't seem to be able to send a mail after doing a task. I have tried various methods. Here is a good illustration of the problem:

I have a method triggered by a post_save signal when a Resource object is saved. In the post_save function I send an email using the standard send_mail. The send_mail function is the only thing in the post_save method.

My scheduled repeating task is able to save new Resources to the database, I can see them in the admin. So I know the tasks are running and are able to interact with the django server. But no email is sent.

When I save a Resource object in the Admin manually. A mail is sent from the post_save function.

Can anyone think of a reason why send_mail might not work in the context of a django-q cluster, even though other django stuff seems to be working ( saving to database for example)?

**Comment by Eagllus** [comment]
@alexgustafson do you have a little more information about your setup?

I have to following setup and works fine.
post_save function calls
``` 
async(send_signup_finished, user, instance.user, group='signup')
```

The `send_signup_finished` will call
```
send_mail(subject, body, '<app>@<domein>', [user.email], fail_silently=True)
```

**Comment by alexgustafson** [comment]
This is the environment:
CentOS Linux release 7.2.1511
Python 2.7.5
tried Django 1.9 and 1.10

Here's what I am testing with at the moment.

`@receiver(post_save, sender=Resource)
def save_resource_handler(sender, **kwargs):

    if not kwargs.get('update_fields'):

        instance = kwargs.get('instance')
        if instance.active and not instance.schedule:
            schedule = Schedule.objects.create(
                func='monitor.models.checkstatus',
                args=instance.pk,
                schedule_type=Schedule.MINUTES,
                minutes=1
            )
            instance.schedule = schedule
            instance.save(update_fields=['schedule'])
`

Basically, a Schedule object is created and linked to a Resource when the resource is marked as active. The Schedule checks every minute if something is ok. The checkstatus method looks like this:

`def checkstatus(resource_id):
    resource = Resource.objects.get(pk=resource_id)
    ok = check_if_ok()

    if not ok:

        status = Status.objects.create(status=ok, resource=resource)
        notify_admin()
`
The notify_admin method simply sends a mail to a fixed email adress at the moment. Nothing dynamic. I have tested the notify_admin() method, it works normally. Just not when the initiator is a django-q task or schedule.

This happening on the server, so I cant debug so easily. Locally I haven't been able to run django-q clusters sind my update to OSX Sierra, so I'm not able to debug here either. I will try to configure my linux laptop to run the project in order to do more debugging.

**Comment by alexgustafson** [comment]
Ok, this is working now. I could localize the problem to my check_if_ok() method as well as some gunicorn/supervisor problems that were conspiring against me. 

Being able to debug locally ( #201 ) helped me solve this. Sorry for the noise, this is a great project!

**Comment by Eagllus** [comment]
@alexgustafson not a problem happy to help!
