### ISSUE TITLE
Tasks in the queue are not being processed

### ISSUE THREAD

**Issue by jordanmkoncz** [Koed00/django-q#203]
Hi, I'm not sure if I'm misunderstanding something about how `django-q` works, but any tasks which I push on to the queue using `async()` seem to just stay in the queue and never get processed, and I'm not sure why.

Here's an example of how I'm pushing tasks onto the queue:

```
async('django.core.mail.send_mail',
              'Test Subject',
              'Test Message',
              'from@example.com',
              [user.email])
```

Below you can see that the tasks are getting registered to the queue, but they just stay in the "Queued tasks" and never get processed.

<img width="916" alt="screen shot 2016-11-10 at 8 26 49 am" src="https://cloud.githubusercontent.com/assets/3453584/20155398/cd47fb40-a71f-11e6-8f68-990b40cde672.png">

My configuration for `django-q` is:
```
Q_CLUSTER = {
    'name': 'DjangoORM',
    'timeout': 30,  # Timeout in secs for a task
    'save_limit': 10,  # Store latest 10 results only
    'orm': 'default'  # Django database connection
}
```

**Comment by jordanmkoncz** [comment]
Disregard; as I suspected, I was misunderstanding how to use django-q. I wasn't running the `python manage.py qcluster` command so I never had a cluster running to actually process tasks in the queue.

It might be beneficial to update the docs so that the "Installation" or "Configuration" sections include some brief instructions or just a mention that the user needs to manually start the cluster so that queued tasks get processed. As someone who had no prior experience with this sort of async queueing functionality before, I didn't actually know this was necessary. It was only when I went through every section of the docs that I eventually realised I needed to manually start the cluster when reading the "Cluster" section.

**Comment by Eagllus** [comment]
Hi @jordanmkoncz in the tasks section there is already a clear note about this.

```
Note
For tasks to be processed you will need to have a worker cluster running in the background using 
python manage.py qcluster or you need to configure Django Q to run in synchronous mode for 
testing using the sync option.
```
the link: http://django-q.readthedocs.io/en/latest/tasks.html?highlight=qcluster#q-options

Cluster explain this in more details.

**Comment by jordanmkoncz** [comment]
@Eagllus Ah yeah, I see that now. I did actually look through the Tasks section of the docs before getting stuck and submitting this issue, but I completely missed that note.

I feel like it would still be better to include some information about this in the "Installation" or "Configuration" section, or perhaps just move this note to one of those sections. Given that the requirement of having a worker cluster running is not specific to single async tasks but rather it applies to using `django-q` in general (both for `async` and `schedule` tasks), it seems like that would help to ensure users are aware of this requirement.

**Comment by Eagllus** [comment]
@jordanmkoncz thanks for the feedback will create a pr about this subject.

After looking in the 'Installation' documentation I believe this idd should be included.

**Comment by Eagllus** [comment]
@jordanmkoncz a short setup about starting a qcluster. #204

**Comment by jordanmkoncz** [comment]
@Eagllus Looks good to me! I think new users (such as myself a few days ago) should see that part of the instructions when setting up `django-q` and be aware from the start that they need to manually start a cluster for `django-q` to actually run the tasks that are scheduled and in the queue.

**Comment by Eagllus** [comment]
I think this issue can be closed, #204 has been merged

**Comment by Eagllus** [comment]
Please reopen this issue if the problem has not been resolved

**Comment by karimone** [comment]
I have the same problem the task in the queue are not processed, but the task in scheduling are processed.

```
Q_CLUSTER = {
    "label": "Tasks",
    "workers": 1,
    "orm": "default",
    "ack_failures": True,
    "timeout": HOUR_IN_SECONDS * 4,
    "retry": HOUR_IN_SECONDS * 24 * 7
}
```
The cache is `memcache 1.5.16`
