### ISSUE TITLE
Add Sentry support

### ISSUE THREAD

**Issue by joeyespo** [Koed00/django-q#210]
I see Rollbar is built in. Could you add support for [Sentry](sentry.io) too?

Alternatively, you could pull out Rollbar into its own `django-q-rollbar` repo (and perhaps use [extras](http://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) so someone can add `django-q[rollbar]` to their `requirements.txt`), and expose a generic error handling interface so others can add their own.

Really enjoying this project btw 😄

**Comment by orangle** [comment]
＋1 . good idea

**Comment by jordanmkoncz** [comment]
+1 I'd definitely use the Sentry support if it was added.

**Comment by danielwelch** [comment]
I took an initial shot at the setuptools extras/entry_points approach for rollbar and sentry support in [my fork](https://github.com/danielwelch/django-q). See [`conf.py`](https://github.com/danielwelch/django-q/blob/error-reporter/django_q/conf.py#L182-L211) for most of the details.

My general idea was to require any plugin to provide an object (I refer to it as [`Reporter`](https://github.com/danielwelch/django-q/blob/error-reporter/django_q/conf.py#L203-L204)) that:
1. exposes a `report()` method, which is called within the context of an exception to report it
2. can be instantiated using configuration provided in the Q_CLUSTER dictionary in settings.py, via the key [`error_reporter`](https://github.com/danielwelch/django-q/blob/error-reporter/django_q/conf.py#L145-L146). This key is mapped to a dictionary of configuration options, which are passed to `Reporter.__init__` as kwargs ([see the rollbar implementation here, for example](https://github.com/danielwelch/django-q-rollbar/blob/master/django_q_rollbar/rollbar.py#L6-L7)). This is similar to how [extra config options are currently passed to `rollbar.init`](https://github.com/Koed00/django-q/blob/master/django_q/conf.py#L180-L190).


I created 2 packages to add support for rollbar and sentry, designed to work with the changes I made: [django-q-rollbar](https://github.com/danielwelch/django-q-rollbar) and [django-q-sentry](https://github.com/danielwelch/django-q-sentry). I [modified setup.py](https://github.com/danielwelch/django-q/blob/error-reporter/setup.py#L59-L68) to register entry points and define the requirements as extras.

Some drawbacks:
- This only allows for configuration though the `Q_CLUSTER` dict, and the current design relies on a plugin developer being able to boil down everything they need to do into one call to `report`. If this is sufficient, I think it's a plus. But I worry those needing more advanced usage of sentry, rollbar, etc. will need more options.
- I added the [`ErrorReporter`](https://github.com/danielwelch/django-q/blob/error-reporter/django_q/conf.py#L182-L192) class mostly to provide a clean interface for handling multiple error reporting mechanisms/plugins, and it feels a little awkward to me. Feedback welcome.


Disclaimer: this is my first stab at writing any python code that takes advantages of extras or entry points. I don't do this professionally, and I'd love any feedback.

**Comment by eskhool** [comment]
👍 Sentry being open source and based on python is an even better fit than roller IMHO

**Comment by Eagllus** [comment]
@danielwelch I have had a look at your code and it looks good.
One important thing that I'm missing is documentation.

I'm not sure if @Koed00 has a problem with 2 extra files in the repo for the ErrorReporters 😉

**Comment by jordanmkoncz** [comment]
Any updates on this guys? :)

**Comment by danielwelch** [comment]
I'd be happy to write up some documentation for using this and developing additional implementations, but I never heard if my approach was acceptable.

**Comment by jordanmkoncz** [comment]
@danielwelch it looks like the approach is acceptable, as @Eagllus is a contributor and seems to have given his approval. @Koed00 maybe you could confirm for us whether this approach would be acceptable?

**Comment by danielwelch** [comment]
@jordanmkoncz Since there still seems to be some interest, I went ahead an added some documentation and submitted a pull request #261. I've also added documentation for my two proposed implementations for [sentry](https://github.com/danielwelch/django-q-sentry) and [rollbar](https://github.com/danielwelch/django-q-rollbar).

**Comment by jordanmkoncz** [comment]
Appreciate the effort @danielwelch, hopefully someone can review and approve the pull request. :)

**Comment by Eagllus** [comment]
Can we close this issue because #261 has been merged?
