### ISSUE TITLE
Mention Django Q Email in the docs?

### ISSUE THREAD

**Issue by joeyespo** [Koed00/django-q#215]
While looking for ways to send email in the background, I found the [email-sending example](https://django-q.readthedocs.io/en/latest/examples.html#emails), but didn't see a straightforward way to use it for built-in email sending like "reset password".

So I just created [Django Q Email](https://github.com/joeyespo/django-q-email) to handle queuing and sending emails in a Django Q background task. After installing it, you can use Django's native email interface like [`send_mail`](https://docs.djangoproject.com/en/1.10/topics/email/#django.core.mail.send_mail) and [`EmailMessage`](https://docs.djangoproject.com/en/1.10/topics/email/#the-emailmessage-class).

Just wanted to share since I've been a big fan of this project 😄 If there's no room in the docs, no worries, feel free to just close.

**Comment by edmenendez** [comment]
I think this is worth mentioning. It's one of the things I was considering a blocker when moving away from Celery.

**Comment by Koed00** [comment]
Done. Linked you in the add-ons section of the Install pages.

**Comment by joeyespo** [comment]
Thanks, @Koed00! 😃 And thanks for Django Q!
