### ISSUE TITLE
django scrapy project can't connect to redis

### ISSUE THREAD

**Issue by davidthewatson** [Koed00/django-q#217]
I have a combined django-scrapy project that sets up django in the scrapy.settings as follows:

    import os
    import sys
    import django

    sys.path.append('../fish')

    os.environ['DJANGO_SETTINGS_MODULE'] = 'fish.settings'

    django.setup()

I have django q setup to run against redis and all the sample code works fine if I run it from django shell. However, running scrapy from the command line:

    scrapy crawl whatever

Fails with:

    redis.exceptions.ConnectionError: Error 61 connecting to localhost:6379. Connection refused.

I can connect with telnet:

    telnet localhost 6379

and the async examples work fine from manage shell

Is there something else I need to call beyond django.setup() in my init scripts above? I've tried adding the redis config directly to the module, but nothing seems to avoid this connection error with redis.

**Comment by Eagllus** [comment]
@davidthewatson I'm not sure if we can help you with this.
I think you should ask people of the `django-scrapy` project.

**Comment by davidthewatson** [comment]
Closing.
