### ISSUE TITLE
How do you actually initiate periodic scheduled tasks in production

### ISSUE THREAD

**Issue by tawanda** [Koed00/django-q#221]
Hi all

with this example

```
from django_q.tasks import schedule

# run `manage.py clearsession` every hour
schedule('django.core.management.call_command',
         'clearsessions',
         schedule_type='H')

```

so i place that in Django's built in AppConfig so that its initiated every time

```
from django.apps import AppConfig
from django_q.tasks import schedule

class MyappConfig(AppConfig):
    name = 'apps.myapp'

    def ready(self):
        schedule('django.core.management.call_command',
                'clearsessions', schedule_type='H')
```

And since this will create a database entry for the periodic task, if i shut down my app and start it again does that mean there will be two identical entries in the database for the same task?

I went through the whole documentation but this last little bit is unclear. Once its explained i can make a PR to the docs to help other people who might be confused about an actual production setup

**Comment by Eagllus** [comment]
Hi @tawanda 

I kinda use the same method but with some extra stuff in there

```
class MyappConfig(AppConfig):
    name = 'apps.myapp'

    def ready(self):
        from django_q.tasks import schedule
        from datetime import datetime
        from django.db import IntegrityError, ProgrammingError, OperationalError

        _date = datetime.now()
        date = datetime(_date.year, _date.month, _date.day)

        schedules = [
            {'func': 'users.tasks.task_generate_users_yaml', 'name': 'Generate users yaml',
             'schedule_type': 'I', 'minutes': 30, 'next_run': date},
        ]

        for info in schedules:
            try:
                schedule(info['func'], name=info['name'], schedule_type=info['schedule_type'], minutes=info['minutes'],
                         next_run=info['next_run'])
            except (ProgrammingError, IntegrityError, OperationalError):
                pass
```

I create a schedules array that I use to insert new `schedules` if there is an error (because it's already exists in the database) the try-catch will capture it and continue.
I deploy at least once a day and haven't had any problems with this method.

**Comment by tawanda** [comment]
@Eagllus Many thanks. That looks sweet will adopt it
