### ISSUE TITLE
The `django_q/tests` directory isn't in the tarball

### ISSUE THREAD

**Issue by abompard** [Koed00/django-q#226]
The `django_q/tests` directory isn't included in the `MANIFEST.in` file, as a result it isn't shipped with the tarball on PyPI, and those users can't run the test suite. Please include it.

**Comment by Eagllus** [comment]
@Koed00 is it possible to share the responsibility to close issues?
It seems quite a few are already resolved but not closed

**Comment by Koed00** [comment]
@Eagllus I've invited you as a collaborator.  That should give you enough rights.
Just pull requests on master are protected.

**Comment by Eagllus** [comment]
@Koed00 thank you, I want meddle in merging pull request. 😉 
This way I can close issues that are resolved/no longer relevant
