### ISSUE TITLE
scheduler creating duplicate tasks in multiple cluster environment

### ISSUE THREAD

**Issue by kefin** [Koed00/django-q#231]
We have a service that uses `django-q` for asynchronous tasks and it's deployed as 2 instances (2 AWS EC2 servers each running the same django project and each running a `django-q` cluster to process tasks). We've encountered an issue where the same scheduled task -- scheduled to run once -- gets picked up by each of the clusters in the `scheduler` (`django-q.cluster`) and ends up having 2 separate tasks being created.

Example entries in our logs:

On server 1:

    2017-04-02 20:25:56,747 - django-q - INFO - Process-1 created a task from schedule [14789]
    2017-04-02 20:25:56,842 - django-q - DEBUG - Pushed ('hamper-india-magnesium-pip', 'f1a1141c1835400ebc4f4b3894922b82')

On server 2:

    2017-04-02 20:25:56,853 - django-q - INFO - Process-1 created a task from schedule [14789]
    2017-04-02 20:25:56,990 - django-q - DEBUG - Pushed ('alpha-william-kansas-apart', '5a4fcadb47674590933415dd5a71e1cc')

Is this the expected behavior or is it a bug?

What we are looking for is to have a scheduled task create only _one_ async task to execute the action, even in a multi-cluster setup like ours.

Can you comment on this behavior?

We're using:

    Django (1.10.6)
    django-q (0.7.18)
    
Thanks

-Kevin

**Comment by Koed00** [comment]
Are the instances sharing a database? 
In that case it could be a bug, where the second process picks up the schedule before the first one manages to lock it. I'll look into this.

**Comment by kefin** [comment]
Yes, we're using AWS RDS (MySQL). Both instances use the same database.

From the log entries, it seems that both the cluster schedulers are picking up the scheduled task with id `14789` and independently creating tasks from this.

**Comment by Koed00** [comment]
Looks like it's happening within less than 100ms, so the process hasn't had time to claim the schedule yet. I could try to block the database query.

While I experiment with that, you could try disabling the scheduler for all but one of the instances

**Comment by kefin** [comment]
To disable the scheduler, do I disable the cluster entirely by not running `python manage.py qcluster`?

Thanks!

**Comment by Koed00** [comment]
You can set `SCHEDULER=False` in the qcluster block of your Django settings and then connect that to an environment setting.

**Comment by kefin** [comment]
OK. Thank you!

**Comment by Koed00** [comment]
sorry, updated the answer cause I'm bad at reading my own documentation ;)

**Comment by bob-r** [comment]
Still getting the same with django 1.8.16 and django-q 0.8.0, on two time-synced servers:

server1:/var/log/syslog
```
May  9 09:02:08 mgr1 manage.py[2753]: 10:02:08 [Q] INFO Enqueued 3184
May  9 09:02:08 mgr1 manage.py[2753]: 10:02:08 [Q] INFO Process-1 created a task from schedule [probe]
May  9 09:02:08 mgr1 manage.py[2753]: 10:02:08 [Q] INFO Enqueued 3186
May  9 09:02:08 mgr1 manage.py[2753]: 10:02:08 [Q] INFO Process-1 created a task from schedule [ticket]
May  9 09:02:08 mgr1 manage.py[2753]: 10:02:08 [Q] INFO Enqueued 3188
May  9 09:02:08 mgr1 manage.py[2753]: 10:02:08 [Q] INFO Process-1 created a task from schedule [notify]
```

server2:/var/log/syslog
```
May  9 09:02:08 mgr2 manage.py[2750]: 10:02:08 [Q] INFO Enqueued 3183
May  9 09:02:08 mgr2 manage.py[2750]: 10:02:08 [Q] INFO Process-1 created a task from schedule [probe]
May  9 09:02:08 mgr2 manage.py[2750]: 10:02:08 [Q] INFO Enqueued 3185
May  9 09:02:08 mgr2 manage.py[2750]: 10:02:08 [Q] INFO Process-1 created a task from schedule [ticket]
May  9 09:02:08 mgr2 manage.py[2750]: 10:02:08 [Q] INFO Enqueued 3187
May  9 09:02:08 mgr2 manage.py[2750]: 10:02:08 [Q] INFO Process-1 created a task from schedule [notify]
```

Questions:
1. Do we prevent the cluster from enqueuing the same task twice (https://github.com/Koed00/django-q/blob/master/django_q/cluster.py#L540)?
2. Should ORM.dequeue be transaction.atomic (https://github.com/Koed00/django-q/blob/master/django_q/brokers/orm.py#L53)?

**Comment by bob-r** [comment]
Regarding my previous message: I see you have addressed this already in 87b87ff9efd452ca7cc620f47d8badc2d823628c.

**Comment by kefin** [comment]
For our project, I have not confirmed the code fix since we have not updated to a recent version of `Django-Q`.

The configuration fix -- setting `scheduler` to `False` in `Q_CLUSTER` in all but one of our servers -- has been able to prevent the duplicate task scheduling.

**Comment by bob-r** [comment]
For resilience, I would prefer to keep multiple schedulers. I tried 87b87ff9efd452ca7cc620f47d8badc2d823628c but it returned: `ERROR select_for_update cannot be used outside of a transaction.`

What works for me (even without select_for_update) is putting the content of try to a transacton.atomic() block (https://github.com/Koed00/django-q/blob/master/django_q/cluster.py#L496).

**Comment by kefin** [comment]
This is an update to this issue. It looks like the current version of `django-q` we're running, v0.9.1, does not fix the issue with the scheduler creating duplicate tasks. We're running 2 servers, each with its own cluster, backed by a MySQL database.

When the `scheduler` function in `cluster.py` does a query for the tasks set to run at the current time, right now there is no mechanism in the code that I see to lock the scheduled task entry or make it "invisible" to schedulers on other clusters. So it's possible for another cluster on another machine to fetch the same schedule task before the first one finishes processing and deletes it. (This is what is happening on our setup -- a scheduled task gets fetched by 2 machines within milliseconds of each other and each cluster ends up creating a task based on the same scheduled entry.)

This means when you have multiple machines running clusters with the scheduler enabled. It is highly likely that each cluster will end up fetching the same schedule task from the database and creating an async task from it.

The solution is as @Koed00 suggested: Disable the scheduler on all but one machine.

I would have preferred that the package implement some kind of locking in the `Schedule` table to prevent multiple fetches of the same task. But we ended up just restricting the scheduler to work on only one machine in our setup.

**Comment by marcelolima** [comment]
I'm also facing the same issue and disabling the schedule on all but one machine is not easy in my case because of auto-scaling. Is there any update on this issue other than the suggested workaround? I noticed there is this PR https://github.com/Koed00/django-q/pull/347 that seems to fix the issue, but still in open.

**Comment by kefin** [comment]
Thank you @Koed00 for merging PR #347.
