### ISSUE TITLE
Django and Django Q on different server with Redis as broker

### ISSUE THREAD

**Issue by wishbooks** [Koed00/django-q#237]
I am trying to separate Django and django-q as my async tasks  are heavy. 

Can anyone please suggest me how can I achieve that?

I tried using remote broker, but it doesn't working

django : 1.7
django-q : 0.7.18
Mysql 5.6 - on django server

**Comment by Eagllus** [comment]
I never tried this with different servers but I would assume you setup your application on both servers (`django` and `django-q`) and make sure both of them can access the Redis queue.

Server 1 (your app server) will receive the requests and queue them in Redis
Server 2 (your background worker server) will read the queue from Redis and processes the queue.

How did you try using remote broker?
https://django-q.readthedocs.io/en/latest/configure.html#redis

```
# redis defaults
Q_CLUSTER = {
    'redis': {
        'host': 'localhost',
        'port': 6379,
        ...
    }
}
```
Setting up Redis on something else then `localhost` (like an ip) should make it available for other servers, if your network settings allow it.

**Comment by wishbooks** [comment]
Thank you!!

It's working now. I checked and found that SECRET_KEY was different even if project name was same. It is resolved now.

**Comment by Eagllus** [comment]
Good to hear, and your always welcome 😄
