### ISSUE TITLE
Avoid retrying failed tasks

### ISSUE THREAD

**Issue by martinzugnoni** [Koed00/django-q#238]
Apparently the default behaviour for failed task is to queue a new task a retry it after certain time.

Is there any way to avoid retrying failed tasks? I mean, if a task raised an error for some reason, do not queue it again, and just display it in the list of "Failed tasks".

It happened to me that a task kept failing for a long time and it was queued again and again.

Thanks!

**Comment by martinzugnoni** [comment]
It's related to this issue: https://github.com/Koed00/django-q/issues/194
But instead of limiting the amount of retries, avoiding them completely.

**Comment by Eagllus** [comment]
Closing this issue as requested
