### ISSUE TITLE
Overflow on repeats fields

### ISSUE THREAD

**Issue by gchardon-hiventy** [Koed00/django-q#255]
Hello
I'm using djang-q with some periodic tasks. 
The most frequent one is started every 5 minutes and thus leads to an overflow on the repeats fields: 11:57:58 [Q] ERROR smallint out of range

This smallint (signed 16bits) overflow occurs after 113 days and raise an exception during model update after the task executing but the remaining scheduled tasks are not executed (the less frequent).

I see two options:
1. Wrap the repeats count since django defines smallint limits
1. Move to "regular" integer 

What do you prefere?

**Comment by Eagllus** [comment]
I think option 2 would be the easiest and best bet.
