### ISSUE TITLE
RFC - Interval for schedules

### ISSUE THREAD

**Issue by thinkwelltwd** [Koed00/django-q#265]
I would like to be able to run tasks on custom intervals, such as every 6 hours, or every 2 weeks, etc. The Minutes schedule type has this feature in that a schedule can be run every specified set of minutes.

In my mind, it would be useful to generalize the "minutes" field to an Interval field so that all schedules types could be run on custom intervals. This would be a backwards incompatible change if the "minutes" column was removed, so I thought I'd ask if there's any interest in such a feature. If there is, I'd be interested in submitting a PR.

Any thoughts?

**Comment by Eagllus** [comment]
I like the idea of having a custom interval.
I don't mind having backwards incompatible changes not sure how @Koed00 thinks about it.
