### ISSUE TITLE
Releases: please use the same tarballs for github and pypi

### ISSUE THREAD

**Issue by P-EB** [Koed00/django-q#280]
Hi,

The tarballs available on github and the ones available on https://pypi.python.org/pypi/django-q differ. Indeed, the former contain the docs/ directory whereas the latter don't.

I discovered this difference while packaging 0.8.1 into Debian. As it's easier to rely on the pypi tarball for the package maintaining, would you consider having the next releases' tarballs be the same on both media?

Thanks a lot! :)

**Comment by Koed00** [comment]
I can add the docs directory to the release, but I'm not sure if I can make both releases identical since they rely on different systems to determine the content.

**Comment by P-EB** [comment]
I guess if you provide the pypi version with the docs, it'll be pretty fine for us. The other part of my question (having identical releases) was more about observing the same exact behaviour for any of your users regardless of the platform they used to get this actual release.

**Comment by P-EB** [comment]
Hi @Koed00, can you add the Changelog.md file into the release tarball you put on pypi? :)

**Comment by Koed00** [comment]
It should be in there. Have a look at the MANIFEST.in

Please not that the MANIFEST files are not included in the wheels.

**Comment by P-EB** [comment]
Yes, indeed, but the MANIFEST.in of django-q 0.9.2 on pypi and github don't contain the include CHANGELOG line. :(

Don't know what happened. :/

**Comment by Koed00** [comment]
I downloaded 0.9.2 myself from pypi and the CHANGELOG.md is in there.
Not sure why it would be different for you.

**Comment by P-EB** [comment]
Oh, my bad. I didn't switch the debian package watchfile to the pypi version.

I thought I did. So actually only the github tarball misses it.

**Comment by P-EB** [comment]
I'll close this issue, as you did your best to have two lookalike releases. :)

Thanks, and cheers!

**Comment by P-EB** [comment]
Ah, there still is no docs/ directory in the pypi release. :(
