### ISSUE TITLE
The model Schedule is already registered

### ISSUE THREAD

**Issue by edebruyne** [Koed00/django-q#285]
Since i update to django 2.0 i can't launch my project with django q enable.
python3.6/site-packages/django_q/admin.py", line 120, in <module>
    admin.site.register(Schedule, ScheduleAdmin)
django.contrib.admin.sites.AlreadyRegistered: The model Schedule is already registered

What can i do ?

**Comment by Eagllus** [comment]
I am running Django 2.0 with Django-Q 0.9 without any problems.
It seems to me you have a other Model that is called Schedule and is already registered.

**Comment by edebruyne** [comment]
That was my first check and i don't have one. Nor the word Schedule inside my entire App.

**Comment by Koed00** [comment]
I also don't have this problem. Could it be you have some other package installed that tries to register that model name?

**Comment by edebruyne** [comment]
Ok that was caused by django_jet. Thanks for your help.

**Comment by Eagllus** [comment]
Anytime
