### ISSUE TITLE
super() call in core_signing.py is python3-only

### ISSUE THREAD

**Issue by P-EB** [Koed00/django-q#294]
Hey,

Me again.

Line 65 (TimeStampSigner:unsign) in `django_q/core_signing.py`, there is a call to super(). This syntax is python3-only.

I suggest this, as long as you intend to maintain both versions:

```
result = super(self.__class__, self).unsign(value)
```

**Comment by Eagllus** [comment]
@P-EB I thought this is fixed in version 0.9.2
https://github.com/Koed00/django-q/blob/c657731cd04610e60ac354a3fbb5145b24b7970b/django_q/core_signing.py#L65

**Comment by P-EB** [comment]
Yes, I saw that recently.

But I recommend to use self.__class__ isntead of TimestampSigner, as it allows portability and class name change.

**Comment by Eagllus** [comment]
That's would not be consistent within the project. 
Everywhere we are using the reference to the same object name.
