### ISSUE TITLE
Tasks are not encrypted, only signed

### ISSUE THREAD

**Issue by asedeno** [Koed00/django-q#300]
The documentation says that tasks are encryped [1], but they are only base64 encoded, optionally compressed, and signed.

```python
>>> from django_q.tasks import async
>>> async('secret.function', 'top-secret-args-that-should-be-encrypted')
'1e5bd61734bb4368bbd6fe205c707615'
>>> import base64, pickle, redis
>>> r = redis.StrictRedis()
>>> payload, salt, sig = r.lindex('django_q:default:q', 0).split(b':')
>>> pickled_data = base64.urlsafe_b64decode(payload)
>>> pickle.loads(pickled_data)
{'args': ('top-secret-args-that-should-be-encrypted',),
 'func': 'secret.function',
 'id': '1e5bd61734bb4368bbd6fe205c707615',
 'kwargs': {},
 'name': 'mars-one-princess-freddie',
 'started': datetime.datetime(2018, 4, 2, 18, 11, 40, 296734, tzinfo=<UTC>)}
```

No key is required to find out what is in a task, so the docs shouldn't say that tasks are encrypted, only that they are signed.

"Tasks are signed. When a worker encounters a task it can not verify, it will be discarded for failed"

[1] http://django-q.readthedocs.io/en/latest/configure.html?highlight=encrypted#name

**Comment by mm-matthias** [comment]
I was also expecting things to be encrypted after I read the docs. If they are not encrypted I'd really like to be able to see the payload in django-admin.
