### ISSUE TITLE
async_task not in docs?!?

### ISSUE THREAD

**Issue by jedie** [Koed00/django-q#317]
It seems to me that the documentation still says "async" and not "async_task", isn't it?

**Comment by tiktuk** [comment]
Yes, it seems like the source is up to date but the docs have not been generated from them.

**Comment by Koed00** [comment]
Turned out to be an issue with ReadtheDocs.
For some reason their build process couldn't find the new Django version.
Fixed by adding a custom _readthedocs.yml config.
