### ISSUE TITLE
Periodic tasks add only if

### ISSUE THREAD

**Issue by fonzmeister** [Koed00/django-q#320]
I use django-q for some background tasks. The tasks looks like this in pseudocode

```
def task(param)
  if param:
    do_something() #runs instantly
  if not param:
    do_something_else() #takes a while to run
    time.sleep(3600)
```

If I run the task every 5 minutes and param == False for a few times in a row I will create a lot of tasks and my queue will overflow. Is there a way that only a new task is created if there is no task running, taking into consideration the timeout?

**Comment by kbuilds** [comment]
Would it be possible to have this task schedule a second task which exectes the long-running code?

That way, the task that is scheduled to run every 5 minutes can check the current queue, and decide whether to schedule another long-running task. Either way, it will finish relatively quickly.

**Comment by fonzmeister** [comment]
I cannot get this to work. I need to pass an object into the function, which is causing me problems, since it can not be pickled
