### ISSUE TITLE
"InterfaceError: connection already closed" being raised when a test is run

### ISSUE THREAD

**Issue by rr-** [Koed00/django-q#326]
This is the same as #198, #144, #127 and #167.

It all boils down to this:

- [`_sync` simulates the whole cluster](https://github.com/Koed00/django-q/blob/master/django_q/tasks.py#L677-L691)
- …but `cluster` is littered with connection closing everywhere:
    - https://github.com/Koed00/django-q/blob/master/django_q/cluster.py#L165
    - https://github.com/Koed00/django-q/blob/master/django_q/cluster.py#L189
    - https://github.com/Koed00/django-q/blob/master/django_q/cluster.py#L370
    - https://github.com/Koed00/django-q/blob/master/django_q/cluster.py#L407
    - https://github.com/Koed00/django-q/blob/master/django_q/cluster.py#L488

As far as I'm concerned this should be using the same safety mechanism as the code [in the original fix](https://github.com/Koed00/django-q/blob/master/django_q/brokers/orm.py#L18).

**Comment by andrlik** [comment]
Seconding this. Right now I'm having to do all sorts of monkeying around in my test suites to test the tasks independently and muting signals like crazy during other tests to prevent this issue from arising. 

It's making it hard to get my test coverage to where it needs to be.
