### ISSUE TITLE
Why is django_q hitting redis so hard?

### ISSUE THREAD

**Issue by shacker** [Koed00/django-q#359]
I have been using django-q against the ORM for quite a while, with success. I recently switched our project over to redis for general caching, which gave me more insight about how the cache is being used. We still want to use Django Admin for task management so I am still specifying `"orm": "default"` in the Q_CLUSTER settings. But I'm seeing some surprising traffic in redis that I can't explain. 

If I run `$ redis-cli monitor` I get this approx. *once per second* even on a secret test server with no traffic, and after confirming that there are no queued jobs - qmonitor and qinfo confirm that there is nothing to do.

```
1558739051.906214 [0 127.0.0.1:45800] "GET" "iris:1:django_q:DjangORM:cluster"
1558739051.906444 [0 127.0.0.1:45800] "SET" "iris:1:django_q:DjangORM:cluster" "\x80\x04\x954\x01\x00\x00\x00\x00\x00\x00]\x94(\x8c\x1fdjango_q:DjangORM:cluster:15849\x94\x8c\x1fdjango_q:DjangORM:cluster:23247\x94\x8c\x1fdjango_q:DjangORM:cluster:25906\x94\x8c\x1fdjango_q:DjangORM:cluster:28570\x94\x8c\x1edjango_q:DjangORM:cluster:1910\x94\x8c\x1edjango_q:DjangORM:cluster:4503\x94\x8c\x1edjango_q:DjangORM:cluster:7636\x94\x8c\x1fdjango_q:DjangORM:cluster:12144\x94\x8c\x1fdjango_q:DjangORM:cluster:15147\x94e."
1558739051.906690 [0 127.0.0.1:45800] "SET" "iris:1:django_q:DjangORM:cluster:15147" "\x80\x04\x95\t\x02\x00\x00\x00\x00\x00\x00X\x02\x02\x00\x00.eJxVUEtOAkEQ1TB8hCgbImzdYQwk7DS9ZGVMxwR1aSYN00DL0D1010QgMdGFrnpH4f93D0_hGTyBN7AHY4K1qKqk8up9Lr35x-rKomwxOGOyp_xR3QCD2KD1jtyCM9y-wgus2uy50gOuDZ5ilc4JvSX0jtB7Qh8IfST0idBnQl8IfSXcpkC10eYCBhzEkC-vM2zms1_pzdJWLd09dCzRBKZu-CfHzYSshTfYQruhuZAdpiUDoaTBgxWb74SxAa59ESDdITZnuAQheYgUic38yS7_GqnHIEJT78ayk3xgIdqSH7LpxI-0Gk_8WEaiMwgTQVVb-YcBzaQJF8Rosz0OwMdJENbbDxzg2sVhc-1YhI7dEaYMaHeFRHYhUJL7I9-IKU80e31lwLkRWpjaojUau3vu61BJAUojfSO2AMwMlkCZKDZ97m7vxK4loTlrwwj7-UVylbJXWP_8xn4xCSpu138AcGOwvw:1hUJER:dwta3zIpSLGycI3lMungW9CGi-U\x94." "PX" "3000"
```

This is surprising in two ways: 

1) I have not told django_q to use caching at all, so why is it hitting redis at all?
2) Why is the traffic to redis from django_q so constant even when there are no jobs to do?

Here are my full q_cluster project settings:

```
Q_CLUSTER = {
    "name": "DjangORM",
    "workers": 10,
    "timeout": 90,
    "retry": None,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
    "ack_failures": True,
}
```

Thanks.

**Comment by shacker** [comment]
Does anyone see similar behavior, or is something unexpected going on?

**Comment by WTFox** [comment]
This looks to be a polling mechanism from this function: 

https://github.com/Koed00/django-q/blob/c84fd11a67c9a47d821786dfcdc189bb258c6f54/django_q/cluster.py#L200

This function runs every half second and checks for any stopped components (workers, monitors, scheduler, etc). Maybe the authors of this library can correct me if I'm wrong.

**Comment by shacker** [comment]
Well-spotted @WTFox, thanks. So it looks like intended behavior. Would be helpful if the docs mentioned this behavior (though I do see now that there is a documented `poll` interval you can set). 

Closing, thanks.
