### ISSUE TITLE
Latest versions of Arrow will break django-q

### ISSUE THREAD

**Issue by natebessa** [Koed00/django-q#377]
Hey everyone,

It looks to me like the latest versions of Arrow are breaking Django-Q's scheduled tasks.

Arrow version 0.14.3, released 13 days ago, introduces a change that [removes "weeks"](https://github.com/crsmithdev/arrow/compare/0.14.3...master#diff-5d8eb9e97f8b648e4dae883cdce7b959L589) and other attributes from its `replace()` function. This method attribute is still being used in the latest version of Django-Q's `scheduler()` method as seen [here](https://github.com/Koed00/django-q/blob/master/django_q/cluster.py#L523).

I recommend that a maximum version of 0.14.2 for Arrow should be added to Django-Q's setup.py install_requires, or Django-Q's scheduler method should be updated and a minimum version of 0.14.3+ of Arrow should be required.

**Comment by Koed00** [comment]
Fixing this right now.

**Comment by eblin** [comment]
Yup this affected us as well, mine was for a few daily tasks we have.

![CleanShot 2019-08-14 at 09 57 32](https://user-images.githubusercontent.com/1273928/63027326-beecfa80-be7a-11e9-96ce-0bd0acad0d2b.png)

Thank you @Koed00 for getting to it quickly, for now I have pinned arrow to 0.14.2
