### ISSUE TITLE
No module named builtins

### ISSUE THREAD

**Issue by nickpolet** [Koed00/django-q#4]
Running the ./manage.py qcluster command with python 2.7 gives you an error:

    from builtins import range
    ImportError: No module named builtins

Looks like the package 'future' is not installed when using pip to install django_q. This issue can be fixed with:

    pip install future

Adding 'future' to the install_requires in setup.py should hopefully fix this little issue.

I have created a pull request at https://github.com/Koed00/django-q/pull/5 to fix this.

**Comment by Koed00** [comment]
'future' handles the backward compatibility from python 3 to 2. Apparently it is not standard on all environments. Thanks.
