### ISSUE TITLE
Question about Multiple Clusters

### ISSUE THREAD

**Issue by barseghyanartur** [Koed00/django-q#401]
Docs state that:

```
You can have multiple clusters on multiple machines, working on the same queue as long as:

They connect to the same broker.
They use the same cluster name. See Configuration
They share the same SECRET_KEY for Django.
```

Does that mean that it's safe to run ```python manage.py qcluster``` on two different nodes (from two different data-centers) without accidental overlap (tasks being executed twice by each of the nodes)?

**Comment by Solanar** [comment]
Depends on the broker, for redis django-q uses `blpop` https://redis.io/commands/blpop which prevents overlap.

**Comment by barseghyanartur** [comment]
@Solanar:

Thanks!
