### ISSUE TITLE
Ability to customize schedule creation

### ISSUE THREAD

**Issue by saranshbansal** [Koed00/django-q#451]
Hi, I'm looking to create a schedule which runs every alternate day. But looking into your documentation, I could only see "some" level of customization on `Minutes` level which is quite frankly useless and inconsistent. 

Can you please consider adding another attribute to the Schedule object for accepting a `cron` like string to make this extension more usable?

Or at least have more options like `minutes=` to allow some level of customization at hourly, daily, monthly, yearly levels. I don't think it would be a lot of work and the use cases for such a feature are in abundance. Please consider adding them in a future release.

**Comment by Koed00** [comment]
For me the scheduler was a bit of an afterthought and I agree it could do with some improvements.
I don't want to write a cron interpreter and then have to maintain it; but I'll look around to see if there are any good cron open source libraries that I can add as an optional install. Maybe something like https://github.com/kiorky/croniter

**Comment by Koed00** [comment]
Cron support through croniter is currently in the master branch while I test it a bit more before release.
