### ISSUE TITLE
Is it the maintainers' intent to support RabbitMQ in the future?

### ISSUE THREAD

**Issue by SebJansen** [Koed00/django-q#454]

**Comment by Koed00** [comment]
Currently there are no plans to support RabbitMQ. Celery is already doing an awesome job for this and I built Django-Q as an alternative if you want to choose another type of broker.  Also the AMPQ protocol needs an active connection with the worker while it does its job to receive an acknowledgement. That doesn't fit with architecture I chose where a seperate process pulls in the tasks and distributes them among the workers. I do follow the developments at RabbitMQ and they've started to support more protocols, so maybe at some point I will try write a broker that is compatible with one of those.

**Comment by SebJansen** [comment]
Quite reasonable, and thanks for your prompt response!
