### ISSUE TITLE
Call Django Class based view function with Django-Q's async_task

### ISSUE THREAD

**Issue by ayasum** [Koed00/django-q#463]
I can't call async_task on a Django class based view function. Considering following case, where I have a DRF view:

```
class Greeter(generics.GenericAPIView)

    def greet(self, name):
        print("Hello: ")
        sleep(5)
        print(name)

    def post(self, request, *args, **kwargs):
        # enqueue the task
        async_task(self.greet, "world")

        return Response(
            {"message": "you should see this right away"}, status=status.HTTP_200_OK
        )
```

When trying to call async_task on a Django class based view function, following errors occur:
- `async_task(self.greet)` returns an `cannot pickle '_io.BufferedReader' object` error
- `async_task("self.greet")` returns an `No module named 'self'` error

I have no issues when putting the `greet` function outside de class.

edit: correcting function names

**Comment by Koed00** [comment]
As a quick fix you could try to async the import path i.e. "Greeter.greet"

**Comment by ayasum** [comment]
> As a quick fix you could try to async the import path i.e. "Greeter.greet"

I tried that as well, but then I have a `No module named` error.

**Comment by Koed00** [comment]
That probably means you are not giving it the full import parth ie:  "myapp.Greeter.greet"

**Comment by mosi-kha** [comment]
hi
 how in case that we need to create an instance of an object then pass that function from the instance, set that function to `async_task`?
ex: `async_task(Test().print_test)` but error some pickle error

**Comment by Koed00** [comment]
Just create a separate task for this:

ie

def print_test(test: Test):
    return test.print_test()

and then async this function with the Test() instance

async_task(my_module.tasks.print_test, Test())


Only the arguments can be instances and will be serialized.

**Comment by rafael-h-ferreira** [comment]
I too have a class with many static methods and I wish to call the class functions. Instead of creating one separate task for each class function, I created one task that will run the class functions:

```
from my_proj import ProjClass
def run_task(class_static_method: str, *args, **kwargs):
    func = getattr(ProjClass, class_static_method)
    return func(*args, **kwargs)
```

Then you may call it like:

`async_task("my_proj.run_task", "class_static_function", arg1)`

Of course, if you need a class instance you need to instantiate it first in the `run_task`. If you also need to pass class args, you probably need a dict arg for the class args and other for the function args.
