### ISSUE TITLE
How to use with test cases? Scheduled tasks are not being queued when running `python manage.py test`.

### ISSUE THREAD

**Issue by bad5ect0r** [Koed00/django-q#490]
Hi. I am trying to build a web application that can periodically run HTTP requests for a set of URLs. I decided to use Django-Q for creating background scheduled tasks to do this. However, I want to write test cases to ensure that I am correctly integrating Django-Q with my models. I start the qcluster and execute the test but it looks like my tasks are not being queued.

This is the test case:

```python
class TestScheduledFetch(TestCase):
    def setUp(self):
        models.Project.objects.create(project_name='TestMe')

    def test_last_fetched_date_updates_on_scheduled_fetch(self):
        url = create_url('TestMe', 'http://www.example.com/', fetch_frequency=models.Url.ONE_MINUTE)
        url.save()
        old_fetch_time = url.last_fetched_date
        time.sleep(70)

        self.assertNotEqual(url.last_fetched_date, old_fetch_time)
```

All it does is check that the scheduled task fetched the URL on its own (it should update the `last_fetched_date` field when it does this. I have a separate test for this and it works.).

When the URL object is saved, it executes this function through a signal receiver listening for the `post_save` signal.

```python
@receiver(post_save, sender=Url)
def create_scheduled_task(sender, instance, created, **kwargs):
    if created:
        schedule(
            'diffresults.tasks.fetch_url',
            instance.id,
            schedule_type='I',
            minutes=1,
            next_run=instance.next_fetch()
        )
```

```python
def fetch_url(url_id):
    url = Url.objects.get(pk=url_id)
    url.fetch()
```

For your reference, this is what the `fetch()` function does.

```python
    def fetch(self):
        resp = self.do_request()
        self.save_into_file(resp.content)
        fetch_date = timezone.now()

        if self.is_file_untracked():
            commit_msg = 'New URL ({}) is now being tracked'.format(self.url_name)
            self.commit(commit_msg)
            self.save()
        elif self.is_file_different():
            commit_msg = 'Change detected on {} at {}'.format(self.url_name, fetch_date)
            self.commit(commit_msg)
            self.save()

        self.last_fetched_date = fetch_date
        self.save()

        return resp
```

I tried searching the documentation for anything related to my situation and I could not find it. Maybe I was not searching it correctly. Does anyone know the best way to do this?

**Comment by bad5ect0r** [comment]
I just want to add that the scheduling works fine when I manually test the app. So there is no problem with the app itself, it's the test script.

**Comment by jonaswinkler** [comment]
You do not need to test that the django-q scheduler is working properly. This is something that should be tested as part of the django-q test suite.

Rather than testing that your task gets executed periodically, you should test that saving a new URL object creates the expected schedule. You can access the schedules in the test case. The rest is taken care of elsewhere.

That also saves lots of time during testing.

**Comment by bad5ect0r** [comment]
Thank you. I think I will close this now.
