### ISSUE TITLE
Django Q is still a young project.

### ISSUE THREAD

**Issue by guettli** [Koed00/django-q#528]
> Django Q is still a young project.

From: https://django-q.readthedocs.io/en/latest/install.html#compatibility

the project is six years old. Do you still think it is young?

**Comment by Koed00** [comment]
There hasn't been much development on it since the early days. Very few major upgrades. So yes, I would still call it young. I guess it's more about maturity through iterations than it is just the passing of time.

**Comment by guettli** [comment]
Thank you for your fast reply. If you think this is still true, then I close this issue.
