### ISSUE TITLE
Custom Job class?

### ISSUE THREAD

**Issue by guettli** [Koed00/django-q#531]
Is there way to store custom Jobs in an own Django model?

I would like to have a db row for every job, and a column for the fields like status, exception-string, input, output, datetime started, datetime ended, ..... in a custom Django model

I see that there is `Task` in models.py.

Is there a way to sub-class this model, to have custom job tables?

In my case I would like to have a row for every existing job. Even for job which are still waiting to get executed.

Performance does not matter in my current context.

Related: https://forum.djangoproject.com/t/store-result-of-task-queue-in-django-model/7434

**Comment by rokdd** [comment]
That would be also for the `Schedule` model nice for having some custom fields and functions.

**Comment by guettli** [comment]
Thank you for the reply. Issue is solved for me.
