### ISSUE TITLE
Queued tasks (OrmQ) are not always acknowledged

### ISSUE THREAD

**Issue by kennyhei** [Koed00/django-q#545]
Here's our current config, we are using Django 2.2.16:

```
VERSION: 1.3.4
ACK_FAILURES: True
BULK: 1
CACHE: default
CACHED: False
CATCH_UP: True
COMPRESSED: False
CPU_AFFINITY: 0
DAEMONIZE_WORKERS: True
DISQUE_FASTACK: False
GUARD_CYCLE: 0.5
LABEL: Django Q
LOG_LEVEL: INFO
MAX_ATTEMPTS: 0
ORM: default
POLL: 0.2
PREFIX: DjangORM
QSIZE: True
QUEUE_LIMIT: 50
Q_STAT: django_q:DjangORM:cluster
RECYCLE: 500
REDIS: {}
RETRY: 2147483647
SAVE_LIMIT: 10000
SCHEDULER: True
SYNC: False
TESTING: False
TIMEOUT: 3300
WORKERS: 4
```

We have 3 clusters and 12 workers in total. QInfo:
<img width="1201" alt="Screenshot 2021-04-29 at 14 25 21" src="https://user-images.githubusercontent.com/1525463/116543683-d55d1300-a8f6-11eb-9cd6-0cdece2fbed1.png">

QMonitor:
<img width="525" alt="Screenshot 2021-04-28 at 17 57 30" src="https://user-images.githubusercontent.com/1525463/116544719-291c2c00-a8f8-11eb-9d75-73a12a2769fb.png">

Sometimes queued tasks are not acknowledged and relevant Task instance (from the OrmQ payload) does not exist. This seems to happen mostly with tasks that have long execution time (200-400 seconds). `TIMEOUT` should be big enough and we get no errors from worker (we are using Sentry for error reporting). Any ideas? Oh and even though the `SAVE_LIMIT` is set to 10000, the limit doesn't always hold i.e. it seems to sometimes ignore this part:
```
        if task["success"] and 0 < Conf.SAVE_LIMIT <= Success.objects.count():
            Success.objects.last().delete()
```

As you can see from `qinfo`, at the moment there are 10485 successful tasks in the database.

**Comment by kennyhei** [comment]
We have fairly frequent deploys, we'll check first how the numbers look like if we don't deploy for a day.

**Comment by Koed00** [comment]
Cool to see you guys use it this much. I have no idea what it could be just
from looking at this.
Do you have some kind of replicating database cluster?

Probably unrelated; I would highly recommend using at least Redis as the
broker.
The ORM one was really only added as a convenience for development, by the
request of users.

**Comment by kennyhei** [comment]
Thanks, we'll look into that. I came up with a fix for the `SAVE_LIMIT` problem in multi-cluster environment by locking the row using `select_for_update` when oldest task is deleted:
```python
with transaction.atomic():
    oldest = Success.objects.select_for_update().last()
    if task["success"] and 0 < Conf.SAVE_LIMIT <= Success.objects.count():
        oldest.delete()
```

Comments? Should I make a PR? @Koed00 
Next I'll try to see what's up with the queued tasks getting stuck, maybe it has something to do with multiple clusters as well.

**Comment by kennyhei** [comment]
I created extra logging app for tasks that usually get stuck since I wasn't sure if the problem is about execution being interrupted or Django Q not being able to mark task as successful / failure (and then acknowledging broker task).

I now know that the execution is stopped before it's finished so we can rule out `monitor`. `pusher` also works correctly, meaning that something happens with `worker`. Timeout shouldn't be the reason.

**Comment by kennyhei** [comment]
Update to the issue with tasks getting stuck:

I created a `qmemory` command for monitoring memory usage.

<img width="1314" alt="Screenshot 2021-05-07 at 4 00 33" src="https://user-images.githubusercontent.com/1525463/117410633-5e89d080-af1b-11eb-898f-e3d3a8e0e453.png">

Lowest available memory (%) for one of the clusters was around ~2% which is pretty low. One of those clusters also has 15min uptime while the others have about 6 hours (since last deployment). We also have one specific task that usually gets stuck to the queue more than the others and during its execution it is reading a big file -> uses lots of memory compared to others.

This seems very promising. I'll test locally if I can recreate this issue by running Django Q out of memory 🙂 If that's the case, I'll probably have to lower `RECYCLE` value or set `MAX_RSS`.

**Comment by Koed00** [comment]
@kennyhei great to see you made so much progress.

If you want to make PR's for this that would be cool.

**Comment by kennyhei** [comment]
@Koed00 Created two PR's, one for `qmemory` and one for `SAVE_LIMIT` bug fix.

**Comment by kennyhei** [comment]
We haven't encountered any problems after lowering the `recycle` setting so that memory is released more frequently. Going to close this issue.
