### ISSUE TITLE
Feature request: override retry for individual tasks

### ISSUE THREAD

**Issue by kennyhei** [Koed00/django-q#551]
Related to https://github.com/Koed00/django-q/issues/545. One way to fix the issue with tasks getting stuck in the queue is to just retry them. But for some tasks I would like to e.g. disable retry (by giving it a large value). Here's an example using ORM broker:

```python
    def _timeout(seconds=None):
        return timezone.now() - timedelta(seconds=seconds or Conf.RETRY)

    def enqueue(self, task):
        # task is signed so this won't work out of the box but shows the idea
        package = self.get_connection().create(
            key=self.list_key, payload=task, lock=_timeout(task.get("retry"))
        )
        return package.pk
```

**Comment by Koed00** [comment]
Closing because problem was fixed with #545 
Retry should be handled by brokers
