### ISSUE TITLE
ability to use override_settings in unit tests to set sync=True

### ISSUE THREAD

**Issue by jnoortheen** [Koed00/django-q#557]
I am using the below pattern 
```
from django.conf import settings
from django.test import override_settings

@override_settings(Q_CLUSTER={**settings.Q_CLUSTER, "sync": True})
 def test_(self):
    ...
```

But this is not updating django-q `Conf`.

**Comment by Matt-Deacalion** [comment]
It seems the **[Conf](https://github.com/Koed00/django-q/blob/master/django_q/conf.py#L31-L203)** class pulls the settings from Django before the test is run, so overriding Django settings has no effect.

If you're using pytest, you could do this:

```python
from django_q.conf import Conf


def test_synchronous(monkeypatch):
    monkeypatch.setattr(Conf, 'SYNC', True)

    # this will be run in synchronous mode…
```

**Comment by jnoortheen** [comment]
closing this since alternative is available
