### ISSUE TITLE
`qcluster` command doesn't handle interrupts. 

### ISSUE THREAD

**Issue by carltongibson** [Koed00/django-q#56]
The management command is intercepting interrupts but then not handling them.

Thus I get an error and can't exit...

```
  File "/Users/carlton/ve/nws/lib/python2.7/site-packages/django_q/cluster.py", line 520, in set_cpu_affinity
    p.cpu_affinity(affinity)
AttributeError: 'Process' object has no attribute 'cpu_affinity'
^C^C^C^C^C^C^C^C^C^C^C
```

I have to kill the shell and start over. It would be nice if `^C` worked here.

**Comment by carltongibson** [comment]
`^C` works after startup — there problem here with an error before then.

**Comment by Koed00** [comment]
The cluster command does explicitly handle interrupts, it's just that the child processes ignore interrupts and only look to the parent process for a stop signal. Which doesn't really work well when that process just crashed. I'll experiment a little to see what can be improved there.

More interesting is your error. I assume you installed ``psuti`l`. So `cpu_affinity` is either not available on your platform or something is happening with the freshly spawned workers.

**Comment by carltongibson** [comment]
> I assume you installed `psutil`. So `cpu_affinity` is either not available on your platform or something is happening with the freshly spawned workers.

Indeed, yes, I installed `psutil`. I'm on OS X (10.10.5)

**Comment by Koed00** [comment]
Unfortunately it seems that ``cpu_affinity`` is just not supported on OS X by ``psuti``l.
Apparently the API for this on OS X didn't exist until 10.5.

All I can do is add a clause to catch this exception.

**Comment by carltongibson** [comment]
OK. That's interesting. 10.5 was a while ago... is there a link to an issue somewhere?

**Comment by Koed00** [comment]
There is this https://github.com/giampaolo/psutil/issues/238 , but it got closed since no one replied to the OS X portion of it.

By the way, if you are just planning on developing on OS X and deploying on a different platform that does support cpu_affinity. You can set the `testing` option in the ``Q_CLUSTER`` dict to ``True`` or ``DEBUG`` and it will use all the code right up to the point that the actual affinity is set. I added this cause the Travis containers don't like cpu affinity either, but I didn't want it to affect my coverage too much.

**Comment by carltongibson** [comment]
OK. Cool. Thanks. (Side note: the `testing` key isn't documented, as yet.)

**Comment by Koed00** [comment]
Is there any chance you could try the Dev branch for me?
I have no access to OSX and Travis does have the cpu_affinity attribute but just crashes on it.

I made it so it will warn you in the log that cpu affinity is not supported and then continue the code as if ``testing`` was set. So you can forgo setting that manually.

**Comment by carltongibson** [comment]
> Is there any chance you could try the Dev branch for me? 

No problem. Will report back later on.
