### ISSUE TITLE
Upgrade to 1.3.6 stops the cluster from working

### ISSUE THREAD

**Issue by michaelbartz** [Koed00/django-q#565]
We upgraded from 1.3.5 to 1.3.6 and our cluster and scheduled jobs quit working.  The error logs are filled with this message:

ERROR localtime() cannot be applied to a naive datetime

**Comment by michaelbartz** [comment]
this is broken on multiple OS's, Linux, Mac, and Ubuntu.  Running Python 3.9.0 to 3.9.5.

**Comment by Koed00** [comment]
My guess would be that you have timezone support disabled in Django. All the tests are being done with `USE_TZ = True`
We'll need to add some check for this before we call localtime, cause this has fixed a bunch of issues for other people.

Will try to make time for this, but any help is appreciated.

**Comment by michaelbartz** [comment]
That was our guess too.  We reverted for now.  We will try to look at this after our next software release.  Thanks for responding.

Michael

From: Ilan Steemers ***@***.***>
Date: Wednesday, May 26, 2021 at 9:01 AM
To: Koed00/django-q ***@***.***>
Cc: Michael Bartz ***@***.***>, Author ***@***.***>
Subject: Re: [Koed00/django-q] Upgrade to 1.3.6 stops the cluster from working (#565)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


My guess would be that you have timezone support disabled in Django. All the tests are being done with USE_TZ = True
We'll need to add some check for this before we call localtime, cause this has fixed a bunch of issues for other people.

Will try to make time for this, but any help is appreciated.

**Comment by Koed00** [comment]
@michaelbartz could you give the master branch a whirl? I think this should fix it.
