### ISSUE TITLE
Migration XYZ dependencies reference nonexistent parent node ('django_q', '0014_auto_20210502_1221')

### ISSUE THREAD

**Issue by philipptrenz** [Koed00/django-q#570]
Hey there,

I'm developing on a local system and deploying on docker for production. Since upgrading and recreating some migrations recently I'm not longer able to migrate the migrations generated on the local dev system on the production system. The related error message:

```
django.db.migrations.exceptions.NodeNotFoundError: Migration rssReader.0001_initial dependencies reference nonexistent parent node ('django_q', '0014_auto_20210502_1221')
``` 

Local dev system:

- Python 3.8.3
- pip 21.1
- django-q 1.3.4
- `lib/python3.8/sites-packages/django_q/migrations/0014_auto_20210502_1221.py` exists

Production system (Docker container):

- Python 3.7.10
- pip 21.1.2
- django-q  1.3.4
- `lib/python3.7/site-packages/django_q/migrations/0014_auto_20210502_1221.py` is missing

Not sure how to deal with this issue, I'm grateful for any help!

**Comment by philipptrenz** [comment]
I think I found the issue: django-q seems to not specify the `default_auto_field`, so that Django created a migration for that and referenced this created migration within my app migrations. Was a bit tricky to resolve, but finally got it.

Is there a way to avoid this behavior for the future?

**Comment by Koed00** [comment]
Good that you figured that one out. That is something from the 3.2 upgrade.  I think this covers it: https://dev.to/rubyflewtoo/upgrading-to-django-3-2-and-fixing-defaultautofield-warnings-518n

I should be able to set the defaults and redo the migrations.

**Comment by philipptrenz** [comment]
Yeah, this should be the issue. Would be great, as the issue will potentially affect many users of django_q 👌🏻
