### ISSUE TITLE
Worker do not work the scheduled task (Docker)

### ISSUE THREAD

**Issue by FakieKickflip** [Koed00/django-q#578]
Hi,

with the development server 
`python manage.py run server `
and 
`python manage.py qcluster`
everything works fine.

Now, I am starting my docker containers. One for the app, one for the Cluster and one for the Postgres.

`    djangoq:
        build: .
        volumes:
            - ./:/django-app
        ports:
            - "8002:8002"
        command: python manage.py qcluster
        depends_on:
            - app   `

The problem is that new scheduled tasks in the (Django ORM as broker) in the database are created but they are not processed when the right time is.

What am I missing? Using python3.8.3:alpine

**Comment by Koed00** [comment]
Can't really tell like this - but I will be working on an example docker version. I'll let you know if I run into the same issue.

**Comment by FakieKickflip** [comment]
I fixed that issue and it was nothing wrong with Django-Q. My app container has an env_file with some database configs in the docker-compose

>         env_file:
>            - ./.env.dev

and I missed to set it for the Django-Q container as well. Both containers need the same configs obviously.

Thanks and sorry for that post.

**Comment by nurettin** [comment]
@FakieKickflip can you please close the issue if you solved your docker setup problem?
