### ISSUE TITLE
Could uWSGI be a broker?

### ISSUE THREAD

**Issue by thinkwelltwd** [Koed00/django-q#59]
I've been watching this project and am very interested. Would it be possible to have uWSGI as a broker for django-q? 

If so, are there any plans to add support?

**Comment by Koed00** [comment]
I actually had a look at this cause it seems a great solution. It certainly has enough functionality to qualify.

The problem I had was not being able to find a way for external processes to connect to a uWSGI queue.
Unlike the cache framework , there doesn't seem a way to create a connection like ``yourcache@192.168.173.22:4040``. To be fair, I have not looked into the uWSGI source code yet. Maybe someone with more experience with uWSGI queues could chime in.

**Comment by thinkwelltwd** [comment]
Well "someone with more experience with uWSGI" wouldn't be my, I'm afraid. Don't know if we could get Roberto to comment or not...

**Comment by Koed00** [comment]
Basically I just need to know how to connect to an uWSGI queue externally, like you can with the cache.

If it turns out it can't be done, it would be an interesting feature request for uWSGI. 
Having a queue only available in-process might even be considered un-uWSGI :)

**Comment by Koed00** [comment]
What I gather from unbit's comment is that we could write some code to listen for external messages that uses the uWSGI queue. It is probably feasible, but I'm a little worried about the architecture of it. Since every Django instance and every cluster instance will have this code, some of which will run under uWSGI, we'd need a way of electing which of these processes is the master queue and deal with respawning etc. I'm not ready to give up on this yet, but I will need to rethink it.

**Comment by thinkwelltwd** [comment]
Well, I'll say that my primary interest in the uWSGI queue is to have a smaller software stack. Now that you've added the ORM broker, you've provided another means to accomplish the same thing.

**Comment by Koed00** [comment]
I'm happy the ORM broker turned out to be useful to you. I wasn't sure when I started on it if anyone would use it.  In that case I think I'll put the uWSGI broker on the long term list for now.

**Comment by thinkwelltwd** [comment]
Yup, I was very pleased with the ORM broker development. That will suit me just perfectly in my situation with a server-admin app, where small stack is great, and high scalability / throughput is a non-issue. Thanks for this excellent package!

**Comment by jpic** [comment]
Many Django apps run with uWSGI in production, which [provides a spooler](http://uwsgi-docs.readthedocs.io/en/latest/Spooler.html). Using the spooler, we would not need to run the qcluster command if I understand django-q correctly (and I probably dont) ?

**Comment by jpic** [comment]
After all I [made my own](https://github.com/yourlabs/django-call) model wrappers around uWSGI spooler (and cron) feature, check it out [if you're curious](https://blog.yourlabs.org/post/177498660443/djcall-005-release).

But django-q was a great inspiration, keep up the great work !
