### ISSUE TITLE
'class' object has no attribute '__name__'

### ISSUE THREAD

**Issue by sepehrsafa** [Koed00/django-q#613]
I’m calling the async_task on a class function. I’m getting the error 'FlightSearch' object has no attribute '__name__'

views.py

```
from .search import FlightSearch
def index(request):

    html = "<html><body>hi</body></html>" 
    FlightSearch(1).search()
    return HttpResponse(html)
```

search.py

```
class FlightSearch(object):

    def __init__(self, originIATACode):
        self.originIATACode = originIATACode

    def niraAvailability(self, api, sharedApi):
        print('test')
        return 1
    
    def search(self):
        async_task(self.niraAvailability,1, 1, group='groupUUID')
```

django q

10:58:11 [Q] INFO Process-1:4 processing [spaghetti-fish-south-robert]
test
10:58:11 [Q] ERROR 'FlightSearch' object has no attribute '__name__'
10:58:11 [Q] INFO Processed [spaghetti-fish-south-robert]

why is that the case?
thanks

**Comment by blaccan** [comment]
Same here

**Comment by roharvey** [comment]
I found this as well. It seemed to come from https://github.com/Koed00/django-q/pull/554, which assumes an object has `__name__`, but it doesn't seem to instantiate it. ~~We passed in the `task_name`, which should really be used here, so~~ I think a fix would look something like:
```
            # convert func to string
            func = task["func"]
            if inspect.isfunction(func):
                func_name = f"{func.__module__}.{func.__name__}"
            elif inspect.ismethod(func) and hasattr(func.__self__, '__name__'):
                func_name = (
                    f"{func.__self__.__module__}."
                    f"{func.__self__.__name__}.{func.__name__}"
                )
            else:
                func_name = str(func)
            Task.objects.create(
                id=task["id"],
                name=task["name"],
                func=func_name,
                hook=task.get("hook"),
                args=task["args"],
                kwargs=task["kwargs"],
                started=task["started"],
                stopped=task["stopped"],
                result=task["result"],
                group=task.get("group"),
                success=task["success"],
                attempt_count=1,
            )
```

I spent some time trying to get the testing environment set up so I could produce tests that showed the regression and the fix, but couldn't follow the directions in README. We'd want to have a class-based test when submitting a PR. The cases above should produce the error just before Task creation (so long as async mode is used).

**Comment by roharvey** [comment]
Oh, and the more helpful thing here! A workaround is simply to add the `__name__` to the class, i.e.:
```
class FlightSearch(object):
    __name__ = 'FlightSearch'

```

Doing so produces the correct "func" string (the same one you get if you run this synchronously, anyway).

**Comment by sepehrsafa** [comment]
> __name__ = 'FlightSearch'

This fixed it! 
Thanks:)
