### ISSUE TITLE
Some tasks are not being processed.

### ISSUE THREAD

**Issue by RomikimoR** [Koed00/django-q#662]
Hello,

I have a django Q cluster running with this configuration:

```
Q_CLUSTER = {
    'name': 'pretty_name',
    'workers': 1,
    'recycle': 500,
    'timeout': 500,
    'queue_limit': 5,
    'cpu_affinity': 1,
    'label': 'Django Q',
    'save_limit': 0,
    'ack_failures': True,
    'max_attempts': 1,
    'attempt_count': 1,
    'redis': {
        'host': CHANNEL_REDIS_HOST,
        'port': CHANNEL_REDIS_PORT,
        'db': 5,
    }

}
```
On this cluster I have a scheduled task supposed to run every 15 minutes.
Sometimes it works fine and this is what I can see on my worker logs:

```
[Q] INFO Enqueued 1
[Q] INFO Process-1 created a task from schedule [2]
[Q] INFO Process-1:1 processing [oranges-georgia-snake-social]
[ My Personal Custom Task Log]
[Q] INFO Processed [oranges-georgia-snake-social]
But other times the task does not start, this is what I get on my log:
```
```

[Q] INFO Enqueued 1
[Q] INFO Process-1 created a task from schedule [2]
```
And then nothing for the next 15 minutes.

Any idea where this might come from ?

**Comment by habeeb03** [comment]
I also faced the same issue. Did you find any solution?

**Comment by RomikimoR** [comment]
No.. If I can't find anything I'll use celery instead I think..

**Comment by RomikimoR** [comment]
hello @habeeb03.

So this was my prod environment and it appears that my dev environment was using the same redis db and even though no task existed on my dev environment it seems that this was the cause of the issue.

The solution was to change the redis db between my dev and prod environment !
