### ISSUE TITLE
Documentation for mocking in case of testing

### ISSUE THREAD

**Issue by ambivalentno** [Koed00/django-q#7]
Greetings.
I've found this library quite interesting, but to start using it (as I follow TDD) it would be really convenient to know how to make asynchronous execution synchronous in case of testing (like CELERY_ALWAYS_EAGER). A friend of mine dropped rq as it was really hard to write tests for tasks code there.

**Comment by Koed00** [comment]
It shouldn't be too hard to add something like that. I'll give it some thought and get back to you.

**Comment by ambivalentno** [comment]
Great. If you also write how to use pdb inside of workers - it will be really good for us.
I mean, sometimes some issues occur in tasks which are really hard to detect without debugger (like, in celery tasks there's no django language context, so translations fail.

**Comment by Koed00** [comment]
It's been a long day and I committed this straight to master. 
I added a `sync=True` option to the `async` command that injects a task straight into a worker and pipes the output through a monitor into the database.

**Comment by Koed00** [comment]
As far as debugging; since everything runs inside a Django context, you can just debug like you would debug your own applications in Django.

**Comment by ambivalentno** [comment]
Great, Thank you!
